DEFAULT_SETTINGS = {'accessibility': {'dimming': {'enabled': False, 'opacity': 50},
                   'pixel_shift': {'enabled': False, 'rate': 4}},
 'custom_preset_backup': {'transitions.block_flip.cols': 24,
                          'transitions.block_flip.rows': 24,
                          'transitions.blockspin.direction': 'Random',
                          'transitions.crumble.crack_complexity': 1.0,
                          'transitions.crumble.piece_count': 16,
                          'transitions.crumble.weighting': 'Random Choice',
                          'transitions.diffuse.block_size': 15,
                          'transitions.diffuse.shape': 'Membrane',
                          'transitions.duration_ms': 5000,
                          'transitions.durations.3D Block Spins': 9000,
                          'transitions.durations.Blinds': 4000,
                          'transitions.durations.Block Puzzle Flip': 5000,
                          'transitions.durations.Crossfade': 5000,
                          'transitions.durations.Crumble': 12000,
                          'transitions.durations.Diffuse': 5500,
                          'transitions.durations.Particle': 10524,
                          'transitions.durations.Ripple': 7200,
                          'transitions.durations.Slide': 5000,
                          'transitions.durations.Warp Dissolve': 6000,
                          'transitions.durations.Wipe': 4000,
                          'transitions.easing': 'Auto',
                          'transitions.particle.direction': 'Left to Right',
                          'transitions.particle.gloss_size': 72.0,
                          'transitions.particle.light_direction': 1,
                          'transitions.particle.mode': 'Swirl',
                          'transitions.particle.overlap': 4.0,
                          'transitions.particle.particle_radius': 9.0,
                          'transitions.particle.swirl_order': 0,
                          'transitions.particle.swirl_strength': 1.0,
                          'transitions.particle.swirl_turns': 3.0,
                          'transitions.particle.texture_mapping': True,
                          'transitions.particle.trail_length': 0.15,
                          'transitions.particle.trail_strength': 0.6,
                          'transitions.particle.use_3d_shading': True,
                          'transitions.particle.wobble': True,
                          'transitions.pool.3D Block Spins': True,
                          'transitions.pool.Blinds': False,
                          'transitions.pool.Block Puzzle Flip': True,
                          'transitions.pool.Crossfade': False,
                          'transitions.pool.Crumble': True,
                          'transitions.pool.Diffuse': True,
                          'transitions.pool.Particle': True,
                          'transitions.pool.Ripple': True,
                          'transitions.pool.Slide': True,
                          'transitions.pool.Warp Dissolve': True,
                          'transitions.pool.Wipe': True,
                          'transitions.random_always': False,
                          'transitions.slide.direction': 'Random',
                          'transitions.type': 'Slide',
                          'transitions.wipe.direction': 'Random',
                          'widgets.clock.analog_face_shadow': True,
                          'widgets.clock.analog_shadow_intense': True,
                          'widgets.clock.bg_color': [35, 35, 35, 255],
                          'widgets.clock.bg_opacity': 0.6,
                          'widgets.clock.border_color': [255, 255, 255, 255],
                          'widgets.clock.border_opacity': 1.0,
                          'widgets.clock.color': [255, 255, 255, 230],
                          'widgets.clock.digital_shadow_intense': False,
                          'widgets.clock.display_mode': 'analog',
                          'widgets.clock.enabled': True,
                          'widgets.clock.font_family': 'Segoe UI',
                          'widgets.clock.font_size': 78,
                          'widgets.clock.format': '24h',
                          'widgets.clock.margin': 30,
                          'widgets.clock.monitor': 'ALL',
                          'widgets.clock.position': 'Top Right',
                          'widgets.clock.show_background': False,
                          'widgets.clock.show_numerals': True,
                          'widgets.clock.show_seconds': True,
                          'widgets.clock.show_timezone': True,
                          'widgets.clock.timezone': 'local',
                          'widgets.clock2.enabled': False,
                          'widgets.clock2.monitor': 2,
                          'widgets.clock2.timezone': 'local',
                          'widgets.clock3.enabled': False,
                          'widgets.clock3.monitor': 'ALL',
                          'widgets.clock3.timezone': 'local',
                          'widgets.media.artwork_size': 250,
                          'widgets.media.bg_color': [35, 35, 35, 255],
                          'widgets.media.bg_opacity': 0.6,
                          'widgets.media.border_color': [255, 255, 255, 255],
                          'widgets.media.border_opacity': 1.0,
                          'widgets.media.color': [255, 255, 255, 230],
                          'widgets.media.enabled': True,
                          'widgets.media.font_family': 'Segoe UI',
                          'widgets.media.font_size': 22,
                          'widgets.media.intense_shadow': True,
                          'widgets.media.margin': 30,
                          'widgets.media.monitor': 2,
                          'widgets.media.position': 'Bottom Left',
                          'widgets.media.provider': 'spotify',
                          'widgets.media.rounded_artwork_border': True,
                          'widgets.media.show_background': True,
                          'widgets.media.show_controls': True,
                          'widgets.media.show_header_frame': True,
                          'widgets.media.spotify_volume_enabled': True,
                          'widgets.media.spotify_volume_fill_color': [255, 255, 255, 230],
                          'widgets.reddit.bg_color': [35, 35, 35, 255],
                          'widgets.reddit.bg_opacity': 0.6,
                          'widgets.reddit.border_color': [255, 255, 255, 255],
                          'widgets.reddit.border_opacity': 1.0,
                          'widgets.reddit.color': [255, 255, 255, 230],
                          'widgets.reddit.enabled': True,
                          'widgets.reddit.exit_on_click': True,
                          'widgets.reddit.font_family': 'Segoe UI',
                          'widgets.reddit.font_size': 14,
                          'widgets.reddit.intense_shadow': True,
                          'widgets.reddit.limit': 10,
                          'widgets.reddit.margin': 30,
                          'widgets.reddit.monitor': 2,
                          'widgets.reddit.position': 'Bottom Right',
                          'widgets.reddit.show_background': True,
                          'widgets.reddit.show_separators': True,
                          'widgets.reddit.subreddit': 'All',
                          'widgets.reddit2.enabled': True,
                          'widgets.reddit2.limit': 20,
                          'widgets.reddit2.monitor': 2,
                          'widgets.reddit2.position': 'Bottom Center',
                          'widgets.reddit2.subreddit': 'Games',
                          'widgets.shadows.blur_radius': 18,
                          'widgets.shadows.color': [0, 0, 0, 255],
                          'widgets.shadows.enabled': True,
                          'widgets.shadows.frame_opacity': 0.77,
                          'widgets.shadows.offset': [4, 4],
                          'widgets.shadows.text_opacity': 0.33,
                          'widgets.spotify_visualizer.adaptive_sensitivity': True,
                          'widgets.spotify_visualizer.bar_border_color': [255, 255, 255, 255],
                          'widgets.spotify_visualizer.bar_border_opacity': 1.0,
                          'widgets.spotify_visualizer.bar_count': 21,
                          'widgets.spotify_visualizer.bar_fill_color': [255, 255, 255, 230],
                          'widgets.spotify_visualizer.dynamic_floor': True,
                          'widgets.spotify_visualizer.dynamic_range_enabled': True,
                          'widgets.spotify_visualizer.enabled': True,
                          'widgets.spotify_visualizer.ghost_alpha': 0.4,
                          'widgets.spotify_visualizer.ghost_decay': 0.35,
                          'widgets.spotify_visualizer.ghosting_enabled': True,
                          'widgets.spotify_visualizer.manual_floor': 0.12,
                          'widgets.spotify_visualizer.mode': 'spectrum',
                          'widgets.spotify_visualizer.sensitivity': 1.0,
                          'widgets.weather.bg_color': [35, 35, 35, 255],
                          'widgets.weather.bg_opacity': 0.6,
                          'widgets.weather.border_color': [255, 255, 255, 255],
                          'widgets.weather.border_opacity': 1.0,
                          'widgets.weather.color': [255, 255, 255, 230],
                          'widgets.weather.enabled': True,
                          'widgets.weather.font_family': 'Segoe UI',
                          'widgets.weather.font_size': 28,
                          'widgets.weather.intense_shadow': True,
                          'widgets.weather.margin': 30,
                          'widgets.weather.monitor': 2,
                          'widgets.weather.position': 'Top Left',
                          'widgets.weather.show_background': True,
                          'widgets.weather.show_forecast': True},
 'display': {'gl_depth_bits': 24,
             'gl_stencil_bits': 8,
             'hw_accel': True,
             'mode': 'fill',
             'prefer_triple_buffer': True,
             'render_backend_mode': 'opengl',
             'same_image_all_monitors': False,
             'sharpen_downscale': False,
             'show_on_monitors': 'ALL',
             'use_lanczos': False},
 'input': {'halo_shape': 'cursor_light', 'hard_exit': False},
 'mc': {},
 'preset': 'custom',
 'queue': {'shuffle': True},
 'sources': {'folders': [],
             'local_ratio': 95,
             'mode': 'folders',
             'rss_background_cap': 30,
             'rss_feeds': [],
             'rss_refresh_minutes': 10,
             'rss_rotating_cache_size': 20,
             'rss_save_directory': '',
             'rss_save_to_disk': False,
             'rss_stale_minutes': 30},
 'timing': {'interval': 140},
 'transitions': {'blinds': {'direction': 'Random', 'feather': 2},
                 'block_flip': {'cols': 24, 'direction': 'Random', 'rows': 24},
                 'blockspin': {'direction': 'Random'},
                 'burn': {'ash_density': 0.8,
                          'ash_enabled': True,
                          'char_width': 0.1,
                          'direction': 'Random',
                          'glow_color': [255, 162, 0, 255],
                          'glow_intensity': 1.0,
                          'jaggedness': 1.0,
                          'smoke_density': 0.8,
                          'smoke_enabled': True},
                 'crumble': {'crack_complexity': 1.0,
                             'piece_count': 16,
                             'weighting': 'Random Choice'},
                 'diffuse': {'block_size': 15, 'shape': 'Membrane'},
                 'direction': 'Random',
                 'duration_ms': 10524,
                 'durations': {'3D Block Spins': 9000,
                               'Blinds': 4000,
                               'Block Puzzle Flip': 5000,
                               'Burn': 8535,
                               'Crossfade': 5000,
                               'Crumble': 12000,
                               'Diffuse': 5500,
                               'Particle': 10524,
                               'Ripple': 7200,
                               'Slide': 5000,
                               'Warp Dissolve': 6000,
                               'Wipe': 4000},
                 'easing': 'Auto',
                 'last_random_choice': 'Block Puzzle Flip',
                 'particle': {'direction': 'Random',
                              'gloss_size': 72.0,
                              'light_direction': 3,
                              'mode': 'Converge',
                              'overlap': 4.0,
                              'particle_radius': 9.0,
                              'swirl_order': 2,
                              'swirl_strength': 1.0,
                              'swirl_turns': 3.5000000000000004,
                              'texture_mapping': True,
                              'trail_length': 0.15,
                              'trail_strength': 0.6,
                              'use_3d_shading': True,
                              'wobble': True},
                 'pool': {'3D Block Spins': True,
                          'Blinds': False,
                          'Block Puzzle Flip': True,
                          'Burn': True,
                          'Crossfade': False,
                          'Crumble': True,
                          'Diffuse': True,
                          'Particle': True,
                          'Ripple': True,
                          'Slide': False,
                          'Warp Dissolve': True,
                          'Wipe': True},
                 'random_always': True,
                 'random_choice': 'Block Puzzle Flip',
                 'ripple': {'ripple_count': 3},
                 'slide': {'direction': 'Random'},
                 'type': 'Particle',
                 'wipe': {'direction': 'Diagonal TL-BR', 'last_direction': 'Diagonal TL-BR'}},
 'ui': {'dialog_geometry': {'height': 900, 'width': 1389, 'x': 113, 'y': 0},
        'last_tab_index': 6,
        'last_tab_scroll': {'accessibility': 0,
                            'display': 0,
                            'presets': 0,
                            'sources': 85,
                            'transitions': 0,
                            'widgets': 230},
        'tab_state': {'widgets': {'view_state': {'scroll': 230, 'subtab': 2}}}},
 'widgets': {'clock': {'analog_face_shadow': True,
                       'analog_shadow_intense': True,
                       'bg_color': [35, 35, 35, 255],
                       'bg_opacity': 0.6,
                       'border_color': [255, 255, 255, 255],
                       'border_opacity': 1.0,
                       'color': [255, 255, 255, 230],
                       'digital_shadow_intense': False,
                       'display_mode': 'analog',
                       'enabled': True,
                       'font_family': 'Segoe UI',
                       'font_size': 78,
                       'format': '24h',
                       'margin': 30,
                       'monitor': 'ALL',
                       'position': 'Top Right',
                       'shared_tick': True,
                       'show_background': False,
                       'show_numerals': True,
                       'show_seconds': True,
                       'show_timezone': True,
                       'timezone': 'local'},
             'clock2': {'color': [255, 255, 255, 230],
                        'display_mode': 'digital',
                        'enabled': False,
                        'font_family': 'Segoe UI',
                        'font_size': 32,
                        'format': '24h',
                        'margin': 30,
                        'monitor': 2,
                        'position': 'Bottom Right',
                        'show_numerals': True,
                        'show_seconds': False,
                        'show_timezone': True,
                        'timezone': 'local'},
             'clock3': {'color': [255, 255, 255, 230],
                        'display_mode': 'digital',
                        'enabled': False,
                        'font_family': 'Segoe UI',
                        'font_size': 32,
                        'format': '24h',
                        'margin': 30,
                        'monitor': 'ALL',
                        'position': 'Bottom Left',
                        'show_numerals': True,
                        'show_seconds': False,
                        'show_timezone': True,
                        'timezone': 'local'},
             'global': {'card_border_width_px': 4},
             'imgur': {'bg_color': [35, 35, 35, 255],
                       'bg_opacity': 0.6,
                       'border_color': [255, 255, 255, 255],
                       'border_opacity': 1.0,
                       'click_opens_browser': True,
                       'color': [255, 255, 255, 230],
                       'custom_tag': '',
                       'enabled': False,
                       'font_family': 'Segoe UI',
                       'font_size': 11,
                       'grid_columns': 4,
                       'grid_rows': 2,
                       'header_font_size': 14,
                       'image_border_color': [255, 255, 255, 255],
                       'image_border_enabled': True,
                       'image_border_radius': 4,
                       'image_border_width': 2,
                       'image_spacing': 4,
                       'intense_shadow': True,
                       'layout_mode': 'hybrid',
                       'margin': 30,
                       'monitor': 2,
                       'position': 'Top Right',
                       'show_background': True,
                       'show_header': True,
                       'tag': 'most_viral',
                       'update_interval': 600},
             'media': {'artwork_size': 250,
                       'bg_color': [35, 35, 35, 255],
                       'bg_opacity': 0.6,
                       'border_color': [255, 255, 255, 255],
                       'border_opacity': 1.0,
                       'color': [255, 255, 255, 230],
                       'enabled': True,
                       'font_family': 'Segoe UI',
                       'font_size': 20,
                       'intense_shadow': True,
                       'margin': 30,
                       'monitor': 2,
                       'mute_button_enabled': True,
                       'position': 'Bottom Left',
                       'provider': 'spotify',
                       'rounded_artwork_border': True,
                       'show_background': True,
                       'show_controls': True,
                       'show_header_frame': True,
                       'spotify_volume_enabled': True,
                       'spotify_volume_fill_color': [79, 79, 79, 150]},
             'reddit': {'bg_color': [35, 35, 35, 255],
                        'bg_opacity': 0.6,
                        'border_color': [255, 255, 255, 255],
                        'border_opacity': 1.0,
                        'color': [255, 255, 255, 230],
                        'enabled': True,
                        'exit_on_click': True,
                        'font_family': 'Segoe UI',
                        'font_size': 14,
                        'intense_shadow': True,
                        'limit': 20,
                        'margin': 30,
                        'monitor': 2,
                        'position': 'Bottom Center',
                        'show_background': True,
                        'show_separators': True,
                        'subreddit': 'All'},
             'reddit2': {'bg_color': [35, 35, 35, 255],
                         'bg_opacity': 0.6,
                         'border_color': [255, 255, 255, 255],
                         'border_opacity': 1.0,
                         'color': [255, 255, 255, 230],
                         'enabled': True,
                         'intense_shadow': True,
                         'limit': 20,
                         'monitor': 2,
                         'position': 'Bottom Right',
                         'show_background': True,
                         'subreddit': 'Games'},
             'shadows': {'blur_radius': 18,
                         'color': [0, 0, 0, 255],
                         'enabled': True,
                         'frame_opacity': 0.77,
                         'offset': [4, 4],
                         'text_opacity': 0.33},
             'spotify_visualizer': {'adaptive_sensitivity': True,
                                    'bar_border_color': [255, 255, 255, 255],
                                    'bar_border_opacity': 1.0,
                                    'bar_count': 21,
                                    'bar_fill_color': [255, 255, 255, 230],
                                    'blob_color': [0, 105, 243, 230],
                                    'blob_constant_wobble': 0.4,
                                    'blob_edge_color': [208, 223, 255, 215],
                                    'blob_glow_color': [3, 104, 255, 180],
                                    'blob_glow_drive_mode': 'bass',
                                    'blob_glow_intensity': 0.5,
                                    'blob_glow_reactivity': 1.0,
                                    'blob_glow_max_size': 1.0,
                                    'blob_growth': 5.0,
                                    'blob_ghosting_enabled': False,
                                    'blob_ghost_alpha': 0.4,
                                    'blob_ghost_decay': 0.3,
                                    'blob_inward_liquid_color': [170, 225, 255, 190],
                                    'blob_inward_liquid_enabled': False,
                                    'blob_inward_liquid_max_size': 0.28,
                                    'blob_inward_liquid_reactivity': 1.0,
                                    'blob_outline_color': [84, 150, 255, 225],
                                    'blob_pulse': 1.88,
                                    'blob_pulse_release_ms': 220,
                                    'blob_reactive_deformation': 0.6,
                                    'blob_reactive_glow': True,
                                    'blob_reactive_wobble': 1.55,
                                    'blob_shaper_audio_motion': 1.2,
                                    'blob_shaper_idle_motion': 0.18,
                                    'blob_size': 0.45,
                                    'blob_stretch': 0.35,
                                    'blob_width': 1.0,
                                    'bubble_big_bass_pulse': 0.8,
                                    'bubble_big_count': 11,
                                    'bubble_big_size_max': 0.03,
                                    'bubble_big_contraction_bias': 1.0,
                                    'bubble_big_size_clamp': 4.0,
                                    'bubble_bounce_big_pct': 70,
                                    'bubble_bounce_small_pct': 30,
                                    'bubble_bounce_big_speed': 0.8,
                                    'bubble_bounce_small_speed': 0.5,
                                    'bubble_bounce_same_only': False,
                                    'bubble_collision_pop_mode': 'off',
                                    'bubble_drift_amount': 0.6,
                                    'bubble_drift_direction': 'random',
                                    'bubble_drift_frequency': 0.7,
                                    'bubble_drift_speed': 0.5,
                                    'bubble_gradient_dark': [7, 42, 53, 255],
                                    'bubble_gradient_light': [0, 179, 255, 255],
                                    'bubble_growth': 5.0,
                                    'devcurve_growth': 3.0,
                                    'bubble_outline_color': [255, 255, 255, 230],
                                    'bubble_pop_color': [68, 68, 68, 255],
                                    'bubble_rotation_amount': 0.3,
                                    'bubble_small_count': 34,
                                    'bubble_small_freq_pulse': 0.56,
                                    'bubble_small_size_max': 0.015,
                                    'bubble_specular_color': [255, 255, 255, 255],
                                    'bubble_specular_direction': 'top_left',
                                    'bubble_gradient_direction': 'top',
                                    'bubble_gradient_semantics_version': 2,
                                    'bubble_stream_constant_speed': 0.14,
                                    'bubble_stream_direction': 'up',
                                    'bubble_stream_reactivity': 1.2,
                                    'bubble_stream_speed_cap': 3.0,
                                    'bubble_surface_reach': 0.81,
                                    'bubble_tail_opacity': 0.0,
                                    'bubble_trail_strength': 0.0,
                                    'bubble_ghosting_enabled': False,
                                    'bubble_ghost_alpha': 0.0,
                                    'bubble_ghost_decay': 0.4,
                                    'devcurve_base_level': 0.58,
                                    'devcurve_motion_power': 1.0,
                                    'devcurve_idle_motion': 0.20,
                                    'devcurve_idle_speed': 0.60,
                                    'devcurve_smoothness': 0.55,
                                    'devcurve_active_layer': 'bass',
                                    'devcurve_layer_bass_enabled': True,
                                    'devcurve_layer_bass_shape_nodes': [[0.0, 0.58], [0.35, 0.64], [0.70, 0.52], [1.0, 0.60]],
                                    'devcurve_layer_bass_color': [82, 167, 255, 230],
                                    'devcurve_layer_bass_outline_color': [255, 255, 255, 255],
                                    'devcurve_layer_bass_outline_width': 0.006,
                                    'devcurve_layer_bass_alpha': 0.55,
                                    'devcurve_layer_bass_power': 1.0,
                                    'devcurve_layer_bass_offset': 0.0,
                                    'devcurve_layer_bass_order': 1,
                                    'devcurve_layer_vocals_enabled': True,
                                    'devcurve_layer_vocals_shape_nodes': [[0.0, 0.58], [0.35, 0.64], [0.70, 0.52], [1.0, 0.60]],
                                    'devcurve_layer_vocals_color': [136, 190, 255, 220],
                                    'devcurve_layer_vocals_outline_color': [255, 255, 255, 255],
                                    'devcurve_layer_vocals_outline_width': 0.006,
                                    'devcurve_layer_vocals_alpha': 0.42,
                                    'devcurve_layer_vocals_power': 1.0,
                                    'devcurve_layer_vocals_offset': -0.01,
                                    'devcurve_layer_vocals_order': 2,
                                    'devcurve_layer_mids_enabled': True,
                                    'devcurve_layer_mids_shape_nodes': [[0.0, 0.58], [0.35, 0.64], [0.70, 0.52], [1.0, 0.60]],
                                    'devcurve_layer_mids_color': [100, 145, 255, 220],
                                    'devcurve_layer_mids_outline_color': [255, 255, 255, 255],
                                    'devcurve_layer_mids_outline_width': 0.006,
                                    'devcurve_layer_mids_alpha': 0.46,
                                    'devcurve_layer_mids_power': 1.0,
                                    'devcurve_layer_mids_offset': 0.01,
                                    'devcurve_layer_mids_order': 3,
                                    'devcurve_layer_transients_enabled': True,
                                    'devcurve_layer_transients_shape_nodes': [[0.0, 0.58], [0.35, 0.64], [0.70, 0.52], [1.0, 0.60]],
                                    'devcurve_layer_transients_color': [215, 240, 255, 240],
                                    'devcurve_layer_transients_outline_color': [255, 255, 255, 255],
                                    'devcurve_layer_transients_outline_width': 0.006,
                                    'devcurve_layer_transients_alpha': 0.66,
                                    'devcurve_layer_transients_power': 1.15,
                                    'devcurve_layer_transients_offset': 0.0,
                                    'devcurve_layer_transients_order': 4,
                                    'devcurve_ghosting_enabled': False,
                                    'devcurve_ghost_alpha': 0.0,
                                    'devcurve_ghost_decay': 0.4,
                                    'devcurve_foreground_shadow_enabled': False,
                                    'devcurve_foreground_shadow_alpha': 0.36,
                                    'devcurve_foreground_shadow_darken': 0.42,
                                    'devcurve_foreground_shadow_offset': 0.10,
                                    'devcurve_foreground_specular_enabled': False,
                                    'devcurve_foreground_specular_alpha': 0.78,
                                    'devcurve_foreground_specular_width': 0.022,
                                    'devcurve_foreground_specular_offset': 0.028,
                                    'devcurve_foreground_specular_crest_bias': 1.05,
                                    'preset_devcurve': 0,
                                    'input_gain': 1.0,
                                    # Technical bucket per-mode defaults
                                    'spectrum_dynamic_floor': True,
                                    'spectrum_manual_floor': 0.12,
                                    'spectrum_dynamic_range_enabled': False,
                                    'spectrum_audio_block_size': 512,
                                    'spectrum_adaptive_sensitivity': True,
                                    'spectrum_sensitivity': 0.4,
                                    'spectrum_bar_count': 33,
                                    'spectrum_agc_strength': 0.5,
                                    'spectrum_input_gain': 1.0,
                                    'spectrum_kick_lane_gain': 1.0,
                                    'spectrum_transient_pulse_gain': 1.0,
                                    'spectrum_transient_clamp': 1.5,
                                    'spectrum_lane_transient_mix': 0.65,
                                    'bubble_dynamic_floor': True,
                                    'bubble_manual_floor': 0.12,
                                    'bubble_dynamic_range_enabled': False,
                                    'bubble_audio_block_size': 512,
                                    'bubble_adaptive_sensitivity': True,
                                    'bubble_sensitivity': 0.4,
                                    'bubble_bar_count': 48,
                                    'bubble_agc_strength': 0.5,
                                    'bubble_input_gain': 1.0,
                                    'bubble_kick_lane_gain': 1.0,
                                    'bubble_transient_pulse_gain': 1.0,
                                    'bubble_transient_clamp': 1.5,
                                    'bubble_transient_mix_bass': 0.75,
                                    'bubble_transient_mix_vocal': 0.25,
                                    'blob_dynamic_floor': True,
                                    'blob_manual_floor': 0.12,
                                    'blob_dynamic_range_enabled': False,
                                    'blob_audio_block_size': 512,
                                    'blob_adaptive_sensitivity': True,
                                    'blob_sensitivity': 0.4,
                                    'blob_bar_count': 32,
                                    'blob_agc_strength': 0.5,
                                    'blob_input_gain': 1.0,
                                    'blob_kick_lane_gain': 1.0,
                                    'blob_transient_pulse_gain': 1.0,
                                    'blob_transient_clamp': 1.5,
                                    'blob_transient_mix_bass': 0.5,
                                    'blob_transient_mix_vocal': 0.35,
                                    'sine_wave_dynamic_floor': True,
                                    'sine_wave_manual_floor': 0.12,
                                    'sine_wave_dynamic_range_enabled': False,
                                    'sine_wave_audio_block_size': 512,
                                    'sine_wave_adaptive_sensitivity': True,
                                    'sine_wave_sensitivity': 0.4,
                                    'sine_wave_bar_count': 40,
                                    'sine_wave_agc_strength': 0.5,
                                    'sine_wave_input_gain': 1.0,
                                    'sine_wave_kick_lane_gain': 1.0,
                                    'sine_wave_transient_pulse_gain': 1.0,
                                    'sine_wave_transient_clamp': 1.5,
                                    'sine_wave_transient_width_mix': 0.4,
                                    'oscilloscope_dynamic_floor': True,
                                    'oscilloscope_manual_floor': 0.12,
                                    'oscilloscope_dynamic_range_enabled': False,
                                    'oscilloscope_audio_block_size': 512,
                                    'oscilloscope_adaptive_sensitivity': True,
                                    'oscilloscope_sensitivity': 0.4,
                                    'oscilloscope_bar_count': 32,
                                    'oscilloscope_agc_strength': 0.5,
                                    'oscilloscope_input_gain': 1.0,
                                    'oscilloscope_kick_lane_gain': 1.0,
                                    'oscilloscope_transient_pulse_gain': 1.0,
                                    'oscilloscope_transient_clamp': 1.5,
                                    'oscilloscope_transient_width_mix': 0.35,
                                    'manual_floor': 0.12,
                                    'agc_strength': 0.5,
                                    'kick_lane_gain': 1.0,
                                    'transient_pulse_gain': 1.0,
                                    'transient_clamp': 1.5,
                                    'mode': 'spectrum',
                                    'monitor': 'ALL',
                                    'osc_ghost_intensity': 0.4,
                                    'osc_ghosting_enabled': True,
                                    'osc_glow_color': [255, 255, 255, 255],
                                    'osc_glow_enabled': True,
                                    'osc_glow_intensity': 0.6,
                                    'osc_glow_reactivity': 1.0,
                                    'osc_glow_size': 1.0,
                                    'osc_growth': 3.01,
                                    'osc_line2_color': [21, 21, 21, 255],
                                    'osc_line2_glow_color': [255, 255, 255, 230],
                                    'osc_ghost_line2_enabled': True,
                                    'osc_line3_color': [21, 21, 21, 250],
                                    'osc_line3_glow_color': [255, 255, 255, 240],
                                    'osc_ghost_line3_enabled': True,
                                    'osc_line4_color': [255, 0, 150, 230],
                                    'osc_line4_glow_color': [255, 0, 150, 180],
                                    'osc_ghost_line4_enabled': True,
                                    'osc_line5_color': [0, 255, 200, 230],
                                    'osc_line5_glow_color': [0, 255, 200, 180],
                                    'osc_ghost_line5_enabled': True,
                                    'osc_line6_color': [200, 100, 255, 230],
                                    'osc_line6_glow_color': [200, 100, 255, 180],
                                    'osc_ghost_line6_enabled': True,
                                    'osc_line_color': [0, 0, 0, 255],
                                    'osc_line_count': 1,
                                    'osc_line_dim': False,
                                    'osc_line_offset_bias': 0.0,
                                    'osc_reactive_glow': True,
                                    'osc_line_amplitude': 4.7,
                                    'osc_smoothing': 0.6,
                                    'osc_speed': 0.33,
                                    'osc_vertical_shift': 25,
                                    'preset_blob': 1,
                                    'preset_bubble': 0,
                                    'preset_oscilloscope': 0,
                                    'preset_sine_wave': 2,
                                    'preset_spectrum': 0,
                                    'rainbow_enabled': True,
                                    'rainbow_speed': 0.3,
                                    'sensitivity': 0.4,
                                    'sine_card_adaptation': 0.3,
                                    'sine_ghosting_enabled': True,
                                    'sine_ghost_alpha': 0.45,
                                    'sine_ghost_decay': 0.3,
                                    'sine_ghost_line2_enabled': True,
                                    'sine_ghost_line3_enabled': True,
                                    'sine_ghost_line4_enabled': True,
                                    'sine_ghost_line5_enabled': True,
                                    'sine_ghost_line6_enabled': True,
                                    'sine_crawl_amount': 0.4,
                                    'sine_density': 1.0,
                                    'sine_displacement': 0.0,
                                    'sine_glow_color': [0, 107, 230, 240],
                                    'sine_glow_enabled': True,
                                    'sine_glow_intensity': 0.6,
                                    'sine_glow_reactivity': 1.0,
                                    'sine_glow_size': 1.0,
                                    'sine_heartbeat': 0.0,
                                    'sine_line1_color': [255, 255, 255, 230],
                                    'sine_line1_shift': 0.0,
                                    'sine_line2_color': [255, 255, 255, 200],
                                    'sine_line2_glow_color': [47, 165, 255, 180],
                                    'sine_line2_shift': 0.35,
                                    'sine_line3_color': [255, 255, 255, 200],
                                    'sine_line3_glow_color': [47, 116, 227, 180],
                                    'sine_line3_shift': -0.35,
                                    'sine_line4_color': [255, 120, 50, 230],
                                    'sine_line4_glow_color': [255, 120, 50, 180],
                                    'sine_line4_shift': 0.0,
                                    'sine_line5_color': [50, 255, 120, 230],
                                    'sine_line5_glow_color': [50, 255, 120, 180],
                                    'sine_line5_shift': 0.0,
                                    'sine_line6_color': [255, 0, 150, 230],
                                    'sine_line6_glow_color': [255, 0, 150, 180],
                                    'sine_line6_shift': 0.0,
                                    'sine_line_color': [255, 255, 255, 240],
                                    'sine_line_count': 3,
                                    'sine_line_dim': False,
                                    'sine_line_offset_bias': 0.0,
                                    'sine_micro_wobble': 0.2,
                                    'sine_reactive_glow': True,
                                    'sine_sensitivity': 2.75,
                                    'sine_smoothing': 0.7,
                                    'sine_speed': 0.7,
                                    'sine_travel_line2': 0,
                                    'sine_travel_line3': 0,
                                    'sine_travel_line4': 0,
                                    'sine_travel_line5': 0,
                                    'sine_travel_line6': 0,
                                    'sine_vertical_shift': 40,
                                    'sine_wave_effect': 0.8,
                                    'sine_wave_growth': 5.0,
                                    'sine_wave_travel': 2,
                                    'sine_width_reaction': 0.0,
                                    'spectrum_lane_strengths_mirrored': {'Mid': 0.60, 'Vocal': 0.64, 'Low-Mid': 0.70, 'Bass': 0.80},
                                    'spectrum_lane_strengths_linear': {'Bass': 0.80, 'Low-Mid': 0.70, 'Vocal': 0.64, 'Hi-Mid': 0.80, 'Treble': 1.00},
                                    'spectrum_mirrored': True,
                                    'spectrum_shape_nodes': [[0.0, 0.40], [0.35, 0.75], [0.65, 0.55], [1.0, 0.80]],
                                    'spectrum_border_radius': 2.0,
                                    'spectrum_link_fill_border': False,
                                    'spectrum_glow_enabled': False,
                                    'spectrum_glow_intensity': 0.55,
                                    'spectrum_glow_color': [110, 220, 255, 235],
                                    'spectrum_growth': 3.96,
                                    'spectrum_profile_floor': 0.12,
                                    'spectrum_unique_colors': True,
                                    'spectrum_render_mode': 'bars',
                                    'spectrum_wave_amplitude': 0.50,
},
             'gmail': {'auto_title_case': True,
                       'bg_color': [35, 35, 35, 255],
                       'bg_opacity': 0.6,
                       'border_color': [255, 255, 255, 255],
                       'border_opacity': 1.0,
                       'color': [255, 255, 255, 230],
                       'desaturate_when_no_unread': True,
                       'enabled': False,
                       'filter_label': 'INBOX',
                       'font_family': 'Segoe UI',
                       'font_size': 14,
                       'intense_shadow': True,
                       'limit': 5,
                       'margin': 30,
                       'monitor': 'ALL',
                       'play_sound_on_new_mail': False,
                       'position': 'Top Left',
                       'refresh_minutes': 5,
                       'show_background': True,
                       'show_envelope_icon': True,
                       'show_sender': True,
                       'show_separators': True,
                       'show_subject': True,
                       'show_three_dot_menu': True,
                       'show_timestamp': True,
                       'show_unread_count_in_header': True,
                       'sound_file_path': 'resources/tutuogg.ogg',
                       'sound_volume_percent': 50},
             'weather': {'bg_color': [35, 35, 35, 255],
                         'bg_opacity': 0.6,
                         'border_color': [255, 255, 255, 255],
                         'border_opacity': 1.0,
                         'color': [255, 255, 255, 230],
                         'detail_icon_size': 16,
                         'enabled': True,
                         'font_family': 'Segoe UI',
                         'font_size': 28,
                         'icon_alignment': 'RIGHT',
                         'icon_size': 96,
                         'intense_shadow': True,
                         'location': '',
                         'margin': 30,
                         'monitor': 2,
                         'position': 'Top Left',
                         'show_background': True,
                         'show_condition_icon': True,
                         'show_details_row': True,
                         'show_forecast': True}},
 'workers': {'fft': {'enabled': False},
             'image': {'enabled': True},
             'max_workers': 'auto',
             'rss': {'enabled': True},
             'transition': {'enabled': True}}}

