"""Canonical Normal-profile defaults.

This literal is the authoritative fresh-install and Reset to Defaults source.
It may be edited directly or through ``tools/default_settings_editor.py``.
Generated defaults artifacts must follow this source rather than override it.
"""
from __future__ import annotations


DEFAULT_SETTINGS = {'accessibility': {'dimming': {'enabled': True, 'opacity': 15},
                   'pixel_shift': {'enabled': False, 'rate': 1}},
 'cache': {'max_concurrent': 2, 'max_items': 16, 'max_memory_mb': 256, 'prefetch_ahead': 5},
 'display': {'gl_depth_bits': 24,
             'gl_stencil_bits': 8,
             'hw_accel': True,
             'mode': 'fill',
             'prefer_triple_buffer': True,
             'render_backend_mode': 'opengl',
             'same_image_all_monitors': False,
             'sharpen_downscale': False,
             'show_on_monitors': 'ALL',
             'use_lanczos': False},
 'input': {'halo_shape': 'cursor_light',
           'interaction_mode': False,
           'widget_glow_color': None,
           'widget_glow_distance': 25,
           'widget_glow_intensity': 80,
           'widget_glow_jedi_mode': False,
           'widget_glow_on_click': False,
           'widget_glow_on_hover': True},
 'queue': {'history_size': 50, 'shuffle': True},
 'sources': {'folders': [],
             'local_ratio': 55,
             'mode': 'folders',
             'rss_background_cap': 30,
             'rss_feeds': [],
             'rss_refresh_minutes': 10,
             'rss_rotating_cache_size': 20,
             'rss_save_directory': '',
             'rss_save_to_disk': False,
             'rss_stale_minutes': 60},
 'timing': {'interval': 40},
 'transitions': {'activation': {'3D Block Spins': True,
                                'Blinds': True,
                                'Block Puzzle Flip': True,
                                'Burn': True,
                                'Crossfade': True,
                                'Crumble': True,
                                'Diffuse': True,
                                'Particle': True,
                                'Ripple': True,
                                'Slide': True,
                                'Warp Dissolve': True,
                                'Wipe': True},
                 'blinds': {'direction': 'Random', 'feather': 2},
                 'block_flip': {'cols': 24, 'direction': 'Random', 'rows': 24},
                 'blockspin': {'direction': 'Random'},
                 'burn': {'ash_density': 0.8,
                          'ash_enabled': True,
                          'char_width': 0.1,
                          'direction': 'Random',
                          'ember_color': [230, 64, 13, 255],
                          'glow_color': [255, 162, 0, 255],
                          'glow_intensity': 1.0,
                          'jaggedness': 1.0,
                          'smoke_density': 0.8,
                          'smoke_enabled': True},
                 'crumble': {'crack_complexity': 1.0,
                             'piece_count': 16,
                             'weighting': 'Random Choice'},
                 'diffuse': {'block_size': 15, 'shape': 'Membrane'},
                 'direction': 'Random',
                 'duration_ms': 10524,
                 'durations': {'3D Block Spins': 9000,
                               'Blinds': 4000,
                               'Block Puzzle Flip': 5000,
                               'Burn': 8535,
                               'Crossfade': 5000,
                               'Crumble': 12000,
                               'Diffuse': 5500,
                               'Particle': 10524,
                               'Ripple': 7200,
                               'Slide': 5000,
                               'Warp Dissolve': 6000,
                               'Wipe': 4000},
                 'particle': {'direction': 'Random',
                              'gloss_size': 72.0,
                              'light_direction': 3,
                              'mode': 'Converge',
                              'overlap': 4.0,
                              'particle_radius': 8.000000000000004,
                              'swirl_order': 2,
                              'swirl_strength': 1.0,
                              'swirl_turns': 3.5000000000000004,
                              'texture_mapping': True,
                              'trail_length': 0.15,
                              'trail_strength': 0.6,
                              'use_3d_shading': True,
                              'wobble': True},
                 'pool': {'3D Block Spins': True,
                          'Blinds': False,
                          'Block Puzzle Flip': True,
                          'Burn': True,
                          'Crossfade': False,
                          'Crumble': True,
                          'Diffuse': True,
                          'Particle': True,
                          'Ripple': True,
                          'Slide': False,
                          'Warp Dissolve': True,
                          'Wipe': True},
                 'random_always': True,
                 'ripple': {'ripple_count': 3},
                 'slide': {'direction': 'Random', 'motion_style': 'Linear'},
                 'type': '3D Block Spins',
                 'wipe': {'direction': 'Bottom to Top'}},
 'ui': {'gmail_bucket_states': {'appearance': False,
                                'backend': False,
                                'layout': False,
                                'separators': True,
                                'sound': False},
        'settings_theme_selection': 'file:Default Dark [Single] [Glass].srtheme',
        'visualizer_adv_states': {'bubble': False,
                                  'devcurve': False,
                                  'oscilloscope': False,
                                  'sine_wave': False,
                                  'spectrum': False,
                                  'sphere': False},
        'visualizer_bucket_states': {'bubble:appearance': False,
                                     'bubble:bounce': False,
                                     'bubble:ghost': False,
                                     'bubble:layout': False,
                                     'bubble:motion': False,
                                     'bubble:population': False,
                                     'bubble:reactivity': False,
                                     'devcurve:core': False,
                                     'devcurve:foreground_fx': False,
                                     'devcurve:ghost': False,
                                     'devcurve:shaper': False,
                                     'oscilloscope:appearance': False,
                                     'oscilloscope:behavior': False,
                                     'oscilloscope:layout': False,
                                     'oscilloscope:multi_line': False,
                                     'sine_wave:appearance': False,
                                     'sine_wave:layout': False,
                                     'sine_wave:motion': False,
                                     'sine_wave:multi_line': False,
                                     'sine_wave:response': False,
                                     'spectrum:appearance': False,
                                     'spectrum:audio': False,
                                     'spectrum:ghost': False,
                                     'spectrum:render': False,
                                     'spectrum:shape': False,
                                     'sphere:motion': False,
                                     'sphere:surface': False},
        'visualizer_tech_bucket_states': {'bubble:agc': False,
                                          'bubble:transient': False,
                                          'devcurve:agc': False,
                                          'devcurve:transient': False,
                                          'oscilloscope:agc': False,
                                          'oscilloscope:transient': False,
                                          'sine_wave:agc': False,
                                          'sine_wave:transient': False,
                                          'spectrum:agc': False,
                                          'spectrum:transient': False},
        'visualizer_tech_states': {'bubble': False,
                                   'devcurve': False,
                                   'oscilloscope': False,
                                   'sine_wave': False,
                                   'spectrum': False},
        'widget_bucket_states': {'clock:additional': False,
                                 'clock:appearance': False,
                                 'clock:layout': False,
                                 'clock:time': False,
                                 'defaults:appearance': False,
                                 'defaults:cache': False,
                                 'defaults:layout': False,
                                 'defaults:style_overrides': False,
                                 'media:appearance': False,
                                 'media:artwork_header': False,
                                 'media:controls': False,
                                 'media:provider_layout': False,
                                 'media:seek_bar': True,
                                 'media:volume_control': False,
                                 'reddit:interaction': False,
                                 'reddit:reddit1': False,
                                 'reddit:secondary': False,
                                 'reddit:shared_appearance': False,
                                 'reddit:shared_layout': False,
                                 'steam:abandonment_issues': False,
                                 'steam:abandonment_issues_appearance': False,
                                 'steam:abandonment_issues_content': False,
                                 'steam:abandonment_issues_layout': False,
                                 'steam:achievement_pulse': False,
                                 'steam:achievement_pulse_appearance': False,
                                 'steam:achievement_pulse_content': False,
                                 'steam:achievement_pulse_layout': False,
                                 'steam:connection': False,
                                 'steam:friend_pulse': False,
                                 'steam:friend_pulse_appearance': False,
                                 'steam:friend_pulse_layout': False,
                                 'steam:steam_progress': False,
                                 'steam:steam_progress_appearance': False,
                                 'steam:steam_progress_layout': False,
                                 'weather:appearance': False,
                                 'weather:content': False,
                                 'weather:source_layout': False}},
 'widget_theme': {'custom': None,
                  'keep_synced': True,
                  'selected_id': 'mirror:file:Default Dark [Single] [Glass].srtheme'},
 'widgets': {'abandonment_issues': {'accent_color': [211, 209, 222, 225],
                                    'artwork_shape': 'portrait',
                                    'artwork_size': 140,
                                    'bg_color': [35, 35, 35, 255],
                                    'bg_opacity': 0.3,
                                    'border_color': [255, 255, 255, 255],
                                    'border_opacity': 1.0,
                                    'color': [255, 255, 255, 230],
                                    'enabled': False,
                                    'font_family': 'Inter',
                                    'font_size': 14,
                                    'guilt_desaturater': False,
                                    'guilt_desaturation_strength': 55,
                                    'header_border_color': [229, 237, 244, 216],
                                    'header_fill_color': [11, 16, 22, 230],
                                    'header_text_color': [255, 255, 255, 230],
                                    'margin': 30,
                                    'minimum_inactivity_weeks': 12,
                                    'minimum_playtime_minutes': 15,
                                    'monitor': '1',
                                    'never_show_appids': [],
                                    'pinned_appid': None,
                                    'position': 'Bottom Right',
                                    'preferred_height': 331,
                                    'preferred_max_playtime_hours': 2,
                                    'preferred_max_unlocked_achievements': 2,
                                    'preferred_minimum_inactivity_weeks': 26,
                                    'preferred_width': 600,
                                    'selection_mode': 'smart_rotation',
                                    'show_achievements': True,
                                    'show_archive_class': False,
                                    'show_artwork': True,
                                    'show_background': True,
                                    'show_last_played': True,
                                    'show_last_unlock': True,
                                    'show_pinned': False,
                                    'show_playtime': True,
                                    'show_queue': False,
                                    'show_rediscovery_message': True,
                                    'show_source': False},
             'achievement_pulse': {'artwork_shape': 'portrait',
                                   'bg_color': [35, 35, 35, 255],
                                   'bg_opacity': 0.3,
                                   'border_color': [255, 255, 255, 255],
                                   'border_opacity': 1.0,
                                   'capsule_border_color': [227, 243, 255, 200],
                                   'capsule_fill_color': [199, 213, 224, 38],
                                   'capsule_font_size': 12,
                                   'color': [255, 255, 255, 230],
                                   'custom_appid': None,
                                   'double_capsules': True,
                                   'enabled': False,
                                   'font_family': 'Inter',
                                   'font_size': 15,
                                   'header_border_color': [229, 237, 244, 216],
                                   'header_fill_color': [11, 16, 22, 230],
                                   'header_text_color': [255, 255, 255, 230],
                                   'latest_unlock_count': 5,
                                   'margin': 30,
                                   'monitor': '1',
                                   'position': 'Bottom Left',
                                   'preferred_height': 334,
                                   'preferred_width': 600,
                                   'selection_mode': 'most_recent',
                                   'show_artwork': True,
                                   'show_background': True,
                                   'show_latest': True,
                                   'show_latest_achievement_artwork': True,
                                   'show_playtime': True,
                                   'show_previous': True,
                                   'show_selected': False,
                                   'show_source': False,
                                   'show_total': True,
                                   'square_artwork_size': 140},
             'clock': {'analog_face_shadow': True,
                       'bg_color': [35, 35, 35, 255],
                       'bg_opacity': 0.3,
                       'border_color': [255, 255, 255, 255],
                       'border_opacity': 1.0,
                       'calendar_font_size': 22,
                       'calendar_layout': 'shared_line',
                       'color': [255, 255, 255, 230],
                       'display_mode': 'analog',
                       'enabled': True,
                       'font_family': 'Inter',
                       'font_size': 78,
                       'format': '24h',
                       'margin': 30,
                       'monitor': '1',
                       'position': 'Top Right',
                       'separator_thickness': 3,
                       'shared_tick': True,
                       'show_background': False,
                       'show_date': False,
                       'show_day_of_week': True,
                       'show_numerals': True,
                       'show_seconds': True,
                       'show_separator': True,
                       'show_timezone': True,
                       'timezone': 'local'},
             'clock2': {'color': [255, 255, 255, 230],
                        'display_mode': 'digital',
                        'enabled': False,
                        'font_family': 'Inter',
                        'font_size': 32,
                        'format': '24h',
                        'margin': 30,
                        'monitor': 1,
                        'position': 'Bottom Right',
                        'show_numerals': True,
                        'show_seconds': False,
                        'show_timezone': True,
                        'timezone': 'local'},
             'clock3': {'color': [255, 255, 255, 230],
                        'display_mode': 'digital',
                        'enabled': False,
                        'font_family': 'Inter',
                        'font_size': 32,
                        'format': '24h',
                        'margin': 30,
                        'monitor': '1',
                        'position': 'Bottom Left',
                        'show_numerals': True,
                        'show_seconds': False,
                        'show_timezone': True,
                        'timezone': 'local'},
             'custom_layout': {'displays': {}, 'version': 2},
             'custom_layout_restore': {'version': 1, 'widgets': {}},
             'family_activation': {'clocks': True,
                                   'gmail': True,
                                   'media': True,
                                   'reddit': True,
                                   'steam': True,
                                   'visualizers': True,
                                   'weather': True},
             'friend_pulse': {'bg_color': [35, 35, 35, 255],
                              'bg_opacity': 0.3,
                              'border_color': [255, 255, 255, 255],
                              'border_opacity': 1.0,
                              'color': [255, 255, 255, 230],
                              'enabled': False,
                              'font_family': 'Inter',
                              'font_size': 14,
                              'margin': 30,
                              'monitor': '1',
                              'position': 'Top Left',
                              'preferred_height': 180,
                              'preferred_width': 420,
                              'show_background': True},
             'global': {'card_border_width_px': 4, 'stacking_enabled': True},
             'gmail': {'account_slot': '0',
                       'auto_title_case': True,
                       'bg_color': [35, 35, 35, 255],
                       'bg_opacity': 0.3,
                       'border_color': [255, 255, 255, 255],
                       'border_opacity': 1.0,
                       'boundary_separator_color': [180, 180, 180, 80],
                       'boundary_separator_thickness': 3,
                       'clean_sender_names': True,
                       'color': [255, 255, 255, 230],
                       'date_display_mode': 'numeric',
                       'desaturate_when_no_unread': False,
                       'enabled': True,
                       'filter_label': 'INBOX',
                       'font_family': 'Inter',
                       'font_size': 12,
                       'group_threads': True,
                       'header_border_color': [255, 255, 255, 255],
                       'header_fill_color': [0, 0, 0, 0],
                       'header_text_color': [255, 255, 255, 230],
                       'limit': 10,
                       'margin': 30,
                       'max_sender_words': 3,
                       'max_subject_words': 4,
                       'monitor': 1,
                       'play_sound_on_new_mail': False,
                       'position': 'Bottom Left',
                       'refresh_minutes': 5,
                       'sender_subject_ratio': 35,
                       'separator_color': [200, 200, 200, 40],
                       'separator_thickness': 3,
                       'show_background': True,
                       'show_envelope_icon': False,
                       'show_header_border': True,
                       'show_refresh_spiral': True,
                       'show_sender': True,
                       'show_separators': True,
                       'show_subject': True,
                       'show_three_dot_menu': True,
                       'show_timestamp': True,
                       'show_unread_count_in_header': True,
                       'sound_file_path': 'resources/tutuogg.ogg',
                       'sound_volume_percent': 25,
                       'width': 600},
             'layout_slots': {'slots': {}, 'version': 1},
             'media': {'artwork_size': 250,
                       'bg_color': [35, 35, 35, 255],
                       'bg_opacity': 0.3,
                       'border_color': [255, 255, 255, 255],
                       'border_opacity': 1.0,
                       'color': [255, 255, 255, 230],
                       'enabled': True,
                       'font_family': 'Inter',
                       'font_size': 17,
                       'header_border_color': [255, 255, 255, 255],
                       'header_fill_color': [0, 0, 0, 0],
                       'header_text_color': [255, 255, 255, 230],
                       'margin': 30,
                       'monitor': 1,
                       'mute_button_enabled': False,
                       'playback_progress_enabled': False,
                       'playback_progress_fill_color': [255, 255, 255, 230],
                       'playback_progress_glow_color': [255, 255, 255, 180],
                       'playback_progress_glow_enabled': False,
                       'playback_progress_height': 6,
                       'playback_progress_shadow_color': [0, 0, 0, 102],
                       'playback_progress_shadow_enabled': False,
                       'playback_progress_track_color': [255, 255, 255, 74],
                       'position': 'Top Left',
                       'provider': 'spotify',
                       'rounded_artwork_border': True,
                       'show_album': True,
                       'show_background': True,
                       'show_controls': True,
                       'show_header_frame': True,
                       'show_playback_state': True,
                       'spotify_volume_border_color': [255, 255, 255, 255],
                       'spotify_volume_enabled': True,
                       'spotify_volume_fill_color': [79, 79, 79, 150],
                       'spotify_volume_track_color': [35, 35, 35, 255]},
             'reddit': {'bg_color': [35, 35, 35, 255],
                        'bg_opacity': 0.3,
                        'border_color': [255, 255, 255, 255],
                        'border_opacity': 1.0,
                        'color': [255, 255, 255, 230],
                        'enabled': True,
                        'exit_on_click': True,
                        'font_family': 'Inter',
                        'font_size': 14,
                        'header_border_color': [255, 255, 255, 255],
                        'header_fill_color': [0, 0, 0, 0],
                        'header_text_color': [255, 255, 255, 230],
                        'limit': 20,
                        'margin': 30,
                        'monitor': 1,
                        'position': 'Bottom Center',
                        'provider': 'rss',
                        'show_background': True,
                        'show_refresh_spiral': True,
                        'show_separators': True,
                        'subreddit': 'All'},
             'reddit2': {'bg_color': [35, 35, 35, 255],
                         'bg_opacity': 0.3,
                         'border_color': [255, 255, 255, 255],
                         'border_opacity': 1.0,
                         'color': [255, 255, 255, 230],
                         'enabled': True,
                         'limit': 20,
                         'margin': 30,
                         'monitor': 1,
                         'position': 'Bottom Right',
                         'show_background': True,
                         'subreddit': 'Games'},
             'shadows': {'blur_radius': 18,
                         'color': [0, 0, 0, 255],
                         'direction': 'SE',
                         'enabled': True,
                         'frame_extra_offset': 0,
                         'frame_opacity': 0.77,
                         'header_enabled': True,
                         'text_enabled': True,
                         'text_extra_offset': 0,
                         'text_opacity': 0.33},
             'spotify_visualizer': {'bubble_adaptive_sensitivity': False,
                                    'bubble_agc_strength': 0.0,
                                    'bubble_audio_block_size': 128,
                                    'bubble_bar_border_color': [255, 255, 255, 255],
                                    'bubble_bar_border_opacity': 1.0,
                                    'bubble_bar_count': 48,
                                    'bubble_bar_fill_color': [12, 12, 12, 230],
                                    'bubble_big_bass_pulse': 0.67,
                                    'bubble_big_contraction_bias': 0.4,
                                    'bubble_big_count': 5,
                                    'bubble_big_size_clamp': 2.96,
                                    'bubble_big_size_max': 0.037,
                                    'bubble_big_specular_max_size': 4.03,
                                    'bubble_big_visual_smoothing': 1.0,
                                    'bubble_bounce_big_pct': 0,
                                    'bubble_bounce_big_speed': 0.0,
                                    'bubble_bounce_same_only': True,
                                    'bubble_bounce_small_pct': 60,
                                    'bubble_bounce_small_speed': 0.1,
                                    'bubble_collision_pop_mode': 'one',
                                    'bubble_drift_amount': 0.35,
                                    'bubble_drift_direction': 'swish_horizontal',
                                    'bubble_drift_frequency': 0.5,
                                    'bubble_drift_speed': 0.15,
                                    'bubble_dynamic_floor': False,
                                    'bubble_dynamic_range_enabled': False,
                                    'bubble_ghost_alpha': 0.15,
                                    'bubble_ghost_decay': 0.5,
                                    'bubble_ghosting_enabled': True,
                                    'bubble_gradient_dark': [0, 4, 11, 255],
                                    'bubble_gradient_direction': 'top',
                                    'bubble_gradient_light': [43, 61, 80, 255],
                                    'bubble_gradient_semantics_version': 2,
                                    'bubble_group_drift': False,
                                    'bubble_input_gain': 0.75,
                                    'bubble_kick_lane_gain': 1.0,
                                    'bubble_manual_floor': 0.3,
                                    'bubble_outline_color': [243, 250, 255, 245],
                                    'bubble_pop_color': [138, 146, 191, 255],
                                    'bubble_rainbow_enabled': False,
                                    'bubble_rainbow_speed': 0.15,
                                    'bubble_rotation_amount': 0.0,
                                    'bubble_sensitivity': 0.55,
                                    'bubble_small_count': 44,
                                    'bubble_small_freq_pulse': 1.1,
                                    'bubble_small_size_max': 0.01,
                                    'bubble_specular_color': [255, 255, 255, 235],
                                    'bubble_specular_direction': 'top_left',
                                    'bubble_stream_constant_speed': 0.15,
                                    'bubble_stream_direction': 'up',
                                    'bubble_stream_reactivity': 1.35,
                                    'bubble_stream_speed_cap': 1.95,
                                    'bubble_surface_reach': 1.0,
                                    'bubble_tail_opacity': 0.8,
                                    'bubble_trail_strength': 0.8,
                                    'bubble_transient_clamp': 1.15,
                                    'bubble_transient_mix_bass': 0.2,
                                    'bubble_transient_mix_vocal': 0.15,
                                    'bubble_transient_pulse_gain': 0.05,
                                    'devcurve_active_layer': 'bass',
                                    'devcurve_adaptive_sensitivity': True,
                                    'devcurve_agc_strength': 0.5,
                                    'devcurve_audio_block_size': 0,
                                    'devcurve_bar_border_color': [255, 255, 255, 255],
                                    'devcurve_bar_border_opacity': 1.0,
                                    'devcurve_bar_count': 32,
                                    'devcurve_bar_fill_color': [255, 255, 255, 230],
                                    'devcurve_base_level': 0.58,
                                    'devcurve_dynamic_floor': True,
                                    'devcurve_dynamic_range_enabled': False,
                                    'devcurve_foreground_shadow_alpha': 0.36,
                                    'devcurve_foreground_shadow_darken': 0.42,
                                    'devcurve_foreground_shadow_enabled': False,
                                    'devcurve_foreground_shadow_offset': 0.1,
                                    'devcurve_foreground_specular_alpha': 0.78,
                                    'devcurve_foreground_specular_crest_bias': 1.05,
                                    'devcurve_foreground_specular_enabled': False,
                                    'devcurve_foreground_specular_offset': 0.028,
                                    'devcurve_foreground_specular_width': 0.022,
                                    'devcurve_ghost_alpha': 0.0,
                                    'devcurve_ghost_decay': 0.4,
                                    'devcurve_ghosting_enabled': False,
                                    'devcurve_idle_motion': 0.2,
                                    'devcurve_idle_speed': 0.6,
                                    'devcurve_input_gain': 1.0,
                                    'devcurve_kick_lane_gain': 1.0,
                                    'devcurve_layer_bass_alpha': 0.55,
                                    'devcurve_layer_bass_color': [82, 167, 255, 230],
                                    'devcurve_layer_bass_enabled': True,
                                    'devcurve_layer_bass_offset': 0.0,
                                    'devcurve_layer_bass_order': 1,
                                    'devcurve_layer_bass_outline_color': [255, 255, 255, 255],
                                    'devcurve_layer_bass_outline_width': 0.006,
                                    'devcurve_layer_bass_power': 1.0,
                                    'devcurve_layer_bass_shape_nodes': [[0.0, 0.58],
                                                                        [0.35, 0.64],
                                                                        [0.7, 0.52],
                                                                        [1.0, 0.6]],
                                    'devcurve_layer_mids_alpha': 0.46,
                                    'devcurve_layer_mids_color': [100, 145, 255, 220],
                                    'devcurve_layer_mids_enabled': True,
                                    'devcurve_layer_mids_offset': 0.01,
                                    'devcurve_layer_mids_order': 3,
                                    'devcurve_layer_mids_outline_color': [255, 255, 255, 255],
                                    'devcurve_layer_mids_outline_width': 0.006,
                                    'devcurve_layer_mids_power': 1.0,
                                    'devcurve_layer_mids_shape_nodes': [[0.0, 0.58],
                                                                        [0.35, 0.64],
                                                                        [0.7, 0.52],
                                                                        [1.0, 0.6]],
                                    'devcurve_layer_transients_alpha': 0.66,
                                    'devcurve_layer_transients_color': [215, 240, 255, 240],
                                    'devcurve_layer_transients_enabled': True,
                                    'devcurve_layer_transients_offset': 0.0,
                                    'devcurve_layer_transients_order': 4,
                                    'devcurve_layer_transients_outline_color': [255, 255, 255, 255],
                                    'devcurve_layer_transients_outline_width': 0.006,
                                    'devcurve_layer_transients_power': 1.15,
                                    'devcurve_layer_transients_shape_nodes': [[0.0, 0.58],
                                                                              [0.35, 0.64],
                                                                              [0.7, 0.52],
                                                                              [1.0, 0.6]],
                                    'devcurve_layer_vocals_alpha': 0.42,
                                    'devcurve_layer_vocals_color': [136, 190, 255, 220],
                                    'devcurve_layer_vocals_enabled': True,
                                    'devcurve_layer_vocals_offset': -0.01,
                                    'devcurve_layer_vocals_order': 2,
                                    'devcurve_layer_vocals_outline_color': [255, 255, 255, 255],
                                    'devcurve_layer_vocals_outline_width': 0.006,
                                    'devcurve_layer_vocals_power': 1.0,
                                    'devcurve_layer_vocals_shape_nodes': [[0.0, 0.58],
                                                                          [0.35, 0.64],
                                                                          [0.7, 0.52],
                                                                          [1.0, 0.6]],
                                    'devcurve_manual_floor': 0.12,
                                    'devcurve_motion_power': 1.0,
                                    'devcurve_rainbow_enabled': False,
                                    'devcurve_rainbow_speed': 0.5,
                                    'devcurve_sensitivity': 1.0,
                                    'devcurve_smoothness': 0.55,
                                    'devcurve_transient_clamp': 1.5,
                                    'devcurve_transient_pulse_gain': 1.0,
                                    'enabled': True,
                                    'enabled_modes': ['spectrum',
                                                      'oscilloscope',
                                                      'sine_wave',
                                                      'bubble',
                                                      'devcurve'],
                                    'mode': 'bubble',
                                    'monitor': '1',
                                    'osc_ghost_decay': 0.4,
                                    'osc_ghost_intensity': 0.4,
                                    'osc_ghost_line2_enabled': True,
                                    'osc_ghost_line3_enabled': True,
                                    'osc_ghost_line4_enabled': True,
                                    'osc_ghost_line5_enabled': True,
                                    'osc_ghost_line6_enabled': True,
                                    'osc_ghosting_enabled': True,
                                    'osc_glow_color': [255, 255, 255, 255],
                                    'osc_glow_enabled': True,
                                    'osc_glow_intensity': 0.6,
                                    'osc_glow_reactivity': 1.0,
                                    'osc_line2_color': [21, 21, 21, 255],
                                    'osc_line2_glow_color': [255, 255, 255, 230],
                                    'osc_line3_color': [21, 21, 21, 250],
                                    'osc_line3_glow_color': [255, 255, 255, 240],
                                    'osc_line4_color': [255, 0, 150, 230],
                                    'osc_line4_glow_color': [255, 0, 150, 180],
                                    'osc_line5_color': [0, 255, 200, 230],
                                    'osc_line5_glow_color': [0, 255, 200, 180],
                                    'osc_line6_color': [200, 100, 255, 230],
                                    'osc_line6_glow_color': [200, 100, 255, 180],
                                    'osc_line_amplitude': 4.7,
                                    'osc_line_color': [0, 0, 0, 255],
                                    'osc_line_count': 1,
                                    'osc_line_dim': False,
                                    'osc_line_offset_bias': 0.0,
                                    'osc_reactive_glow': True,
                                    'osc_smoothing': 0.6,
                                    'osc_speed': 0.33,
                                    'osc_vertical_shift': 25,
                                    'oscilloscope_adaptive_sensitivity': True,
                                    'oscilloscope_agc_strength': 0.5,
                                    'oscilloscope_audio_block_size': 512,
                                    'oscilloscope_bar_border_color': [255, 255, 255, 255],
                                    'oscilloscope_bar_border_opacity': 1.0,
                                    'oscilloscope_bar_count': 32,
                                    'oscilloscope_bar_fill_color': [255, 255, 255, 230],
                                    'oscilloscope_dynamic_floor': True,
                                    'oscilloscope_dynamic_range_enabled': False,
                                    'oscilloscope_input_gain': 1.0,
                                    'oscilloscope_kick_lane_gain': 1.0,
                                    'oscilloscope_manual_floor': 0.12,
                                    'oscilloscope_rainbow_enabled': False,
                                    'oscilloscope_rainbow_speed': 0.5,
                                    'oscilloscope_sensitivity': 0.4,
                                    'oscilloscope_transient_clamp': 1.5,
                                    'oscilloscope_transient_pulse_gain': 1.0,
                                    'oscilloscope_transient_width_mix': 0.35,
                                    'position': 'Follow Media',
                                    'preset_bubble': 0,
                                    'preset_devcurve': 0,
                                    'preset_oscilloscope': 0,
                                    'preset_sine_wave': 4,
                                    'preset_spectrum': 0,
                                    'preset_sphere': 0,
                                    'rainbow_enabled': False,
                                    'rainbow_speed': 0.15,
                                    'sine_card_adaptation': 0.24,
                                    'sine_crawl_amount': 0.0,
                                    'sine_density': 1.6,
                                    'sine_displacement': 0.0,
                                    'sine_ghost_alpha': 0.12,
                                    'sine_ghost_decay': 0.68,
                                    'sine_ghost_line2_enabled': True,
                                    'sine_ghost_line3_enabled': True,
                                    'sine_ghost_line4_enabled': True,
                                    'sine_ghost_line5_enabled': True,
                                    'sine_ghost_line6_enabled': True,
                                    'sine_ghosting_enabled': True,
                                    'sine_glow_color': [148, 188, 255, 218],
                                    'sine_glow_enabled': True,
                                    'sine_glow_intensity': 0.42,
                                    'sine_glow_reactivity': 1.3,
                                    'sine_heartbeat': 0.0,
                                    'sine_line1_shift': 0.0,
                                    'sine_line2_color': [192, 224, 255, 198],
                                    'sine_line2_glow_color': [160, 178, 255, 178],
                                    'sine_line2_shift': 0.22,
                                    'sine_line3_color': [230, 196, 255, 190],
                                    'sine_line3_glow_color': [202, 148, 255, 172],
                                    'sine_line3_shift': -0.22,
                                    'sine_line4_color': [255, 120, 50, 230],
                                    'sine_line4_glow_color': [255, 120, 50, 180],
                                    'sine_line4_shift': 0.0,
                                    'sine_line5_color': [50, 255, 120, 230],
                                    'sine_line5_glow_color': [50, 255, 120, 180],
                                    'sine_line5_shift': 0.0,
                                    'sine_line6_color': [255, 0, 150, 230],
                                    'sine_line6_glow_color': [255, 0, 150, 180],
                                    'sine_line6_shift': 0.0,
                                    'sine_line_color': [255, 255, 255, 228],
                                    'sine_line_count': 3,
                                    'sine_line_dim': False,
                                    'sine_line_offset_bias': 0.12,
                                    'sine_micro_wobble': 0.08,
                                    'sine_reactive_glow': True,
                                    'sine_sensitivity': 0.36,
                                    'sine_smoothing': 0.7,
                                    'sine_speed': 0.42,
                                    'sine_travel_line2': 0,
                                    'sine_travel_line3': 0,
                                    'sine_travel_line4': 0,
                                    'sine_travel_line5': 0,
                                    'sine_travel_line6': 0,
                                    'sine_vertical_shift': 44,
                                    'sine_wave_adaptive_sensitivity': True,
                                    'sine_wave_agc_strength': 0.62,
                                    'sine_wave_audio_block_size': 256,
                                    'sine_wave_bar_border_color': [255, 255, 255, 255],
                                    'sine_wave_bar_border_opacity': 1.0,
                                    'sine_wave_bar_count': 40,
                                    'sine_wave_bar_fill_color': [0, 0, 0, 130],
                                    'sine_wave_dynamic_floor': True,
                                    'sine_wave_dynamic_range_enabled': False,
                                    'sine_wave_effect': 0.3,
                                    'sine_wave_input_gain': 0.44,
                                    'sine_wave_kick_lane_gain': 0.85,
                                    'sine_wave_manual_floor': 0.12,
                                    'sine_wave_rainbow_enabled': False,
                                    'sine_wave_rainbow_speed': 0.22,
                                    'sine_wave_sensitivity': 0.36,
                                    'sine_wave_transient_clamp': 1.0,
                                    'sine_wave_transient_pulse_gain': 1.0,
                                    'sine_wave_transient_width_mix': 0.32,
                                    'sine_wave_travel': 2,
                                    'sine_width_reaction': 0.18,
                                    'spectrum_adaptive_sensitivity': True,
                                    'spectrum_agc_strength': 0.5,
                                    'spectrum_audio_block_size': 512,
                                    'spectrum_bar_border_color': [255, 255, 255, 255],
                                    'spectrum_bar_border_opacity': 1.0,
                                    'spectrum_bar_count': 33,
                                    'spectrum_bar_fill_color': [12, 12, 12, 230],
                                    'spectrum_border_radius': 2.0,
                                    'spectrum_drop_speed': 1.0,
                                    'spectrum_dynamic_floor': True,
                                    'spectrum_dynamic_range_enabled': False,
                                    'spectrum_ghost_alpha': 0.4,
                                    'spectrum_ghost_decay': 0.35,
                                    'spectrum_ghosting_enabled': True,
                                    'spectrum_glow_color': [110, 220, 255, 235],
                                    'spectrum_glow_enabled': False,
                                    'spectrum_glow_intensity': 0.55,
                                    'spectrum_input_gain': 1.0,
                                    'spectrum_kick_lane_gain': 1.0,
                                    'spectrum_lane_strengths_linear': {'Bass': 0.8,
                                                                       'Hi-Mid': 0.8,
                                                                       'Low-Mid': 0.7,
                                                                       'Treble': 1.0,
                                                                       'Vocal': 0.64},
                                    'spectrum_lane_strengths_mirrored': {'Bass': 0.8,
                                                                         'Low-Mid': 0.7,
                                                                         'Mid': 0.6,
                                                                         'Vocal': 0.64},
                                    'spectrum_lane_transient_mix': 0.65,
                                    'spectrum_link_fill_border': False,
                                    'spectrum_manual_floor': 0.12,
                                    'spectrum_mirrored': True,
                                    'spectrum_notch_positions_linear': [[0.0, 'Bass'],
                                                                        [0.24, 'Low-Mid'],
                                                                        [0.46, 'Vocal'],
                                                                        [0.72, 'Hi-Mid'],
                                                                        [1.0, 'Treble']],
                                    'spectrum_notch_positions_mirrored': [[0.0, 'Mid'],
                                                                          [0.3, 'Vocal'],
                                                                          [0.65, 'Low-Mid'],
                                                                          [1.0, 'Bass']],
                                    'spectrum_profile_floor': 0.12,
                                    'spectrum_rainbow_border': False,
                                    'spectrum_rainbow_enabled': False,
                                    'spectrum_rainbow_fill': True,
                                    'spectrum_rainbow_speed': 0.5,
                                    'spectrum_render_mode': 'bars',
                                    'spectrum_sensitivity': 0.4,
                                    'spectrum_shape_nodes': [[0.0, 0.4],
                                                             [0.35, 0.75],
                                                             [0.65, 0.55],
                                                             [1.0, 0.8]],
                                    'spectrum_transient_clamp': 1.5,
                                    'spectrum_transient_pulse_gain': 1.0,
                                    'spectrum_unique_colors': True,
                                    'spectrum_visual_smoothing': 0.5,
                                    'spectrum_visual_smoothing_enabled': True,
                                    'spectrum_wave_amplitude': 0.5,
                                    'sphere_allow_overflow': False,
                                    'sphere_bass_response': 1.45,
                                    'sphere_cel_shading': False,
                                    'sphere_light_tracer_enabled': False,
                                    'sphere_fragment_interpolation_enabled': False,
                                    'sphere_rainbow_ghosting': False,
                                    'sphere_shadow_enabled': True,
                                    'sphere_bump_reactivity': 0.85,
                                    'sphere_deformation': 1.35,
                                    'sphere_energy_curve': 0.62,
                                    'sphere_fade_incoming_blocks': False,
                                    'sphere_gloss': 0.2,
                                    'sphere_high_response': 0.6,
                                    'sphere_idle_motion': 0.0,
                                    'sphere_light_direction': 'NW',
                                    'sphere_finish': 'Neutral',
                                    'sphere_fill_color': [95, 160, 190, 255],
                                    'sphere_edge_color': [190, 224, 234, 255],
                                    'sphere_mid_response': 0.9,
                                    'sphere_base_rotation_speed': 0.026,
                                    'sphere_rotation_speed': 0.32,
                                    'sphere_size_response': 1.15,
                                    'sphere_specular': 0.25,
                                    'sphere_surface_detail': 0.55,
                                    'sphere_vocal_response': 0.95,
                                    'visualizers_enabled': True},
             'steam': {'enabled': False,
                       'privacy_mode': 'Rich',
                       'refresh_minutes': 6,
                       'show_connection_info_icon': True},
             'steam_progress': {'bg_color': [35, 35, 35, 255],
                                'bg_opacity': 0.3,
                                'border_color': [255, 255, 255, 255],
                                'border_opacity': 1.0,
                                'color': [255, 255, 255, 230],
                                'enabled': False,
                                'font_family': 'Inter',
                                'font_size': 14,
                                'margin': 30,
                                'monitor': '1',
                                'position': 'Top Right',
                                'preferred_height': 180,
                                'preferred_width': 420,
                                'show_background': True},
             'weather': {'bg_color': [35, 35, 35, 255],
                         'bg_opacity': 0.3,
                         'border_color': [255, 255, 255, 255],
                         'border_opacity': 1.0,
                         'color': [255, 255, 255, 230],
                         'detail_icon_size': 16,
                         'enabled': True,
                         'font_family': 'Inter',
                         'font_size': 25,
                         'icon_alignment': 'RIGHT',
                         'icon_size': 96,
                         'location': '',
                         'margin': 30,
                         'monitor': 1,
                         'position': 'Bottom Right',
                         'show_background': True,
                         'show_condition_icon': True,
                         'show_details_row': True,
                         'show_forecast': True}},
 'workers': {'fft': {'enabled': False},
             'image': {'enabled': True},
             'max_workers': 'auto',
             'rss': {'enabled': True},
             'transition': {'enabled': True}}}
