"""Canonical Normal-profile defaults.

This literal is the authoritative fresh-install and Reset to Defaults source.
It may be edited directly or through ``tools/default_settings_editor.py``.
Generated defaults artifacts must follow this source rather than override it.
"""
from __future__ import annotations


DEFAULT_SETTINGS = {'accessibility': {'dimming': {'enabled': False, 'opacity': 40},
                   'dimming.enabled': True,
                   'dimming.opacity': 15,
                   'pixel_shift': {'enabled': False, 'rate': 4},
                   'pixel_shift.enabled': True,
                   'pixel_shift.rate': 1},
 'custom_preset_backup': {'transitions.block_flip.cols': 24,
                          'transitions.block_flip.rows': 24,
                          'transitions.blockspin.direction': 'Random',
                          'transitions.crumble.crack_complexity': 1.0,
                          'transitions.crumble.piece_count': 16,
                          'transitions.crumble.weighting': 'Random Choice',
                          'transitions.diffuse.block_size': 15,
                          'transitions.diffuse.shape': 'Membrane',
                          'transitions.duration_ms': 5000,
                          'transitions.durations.3D Block Spins': 9000,
                          'transitions.durations.Blinds': 4000,
                          'transitions.durations.Block Puzzle Flip': 5000,
                          'transitions.durations.Crossfade': 5000,
                          'transitions.durations.Crumble': 12000,
                          'transitions.durations.Diffuse': 5500,
                          'transitions.durations.Particle': 10524,
                          'transitions.durations.Ripple': 7200,
                          'transitions.durations.Slide': 5000,
                          'transitions.durations.Warp Dissolve': 6000,
                          'transitions.durations.Wipe': 4000,
                          'transitions.particle.direction': 'Left to Right',
                          'transitions.particle.gloss_size': 72.0,
                          'transitions.particle.light_direction': 1,
                          'transitions.particle.mode': 'Swirl',
                          'transitions.particle.overlap': 4.0,
                          'transitions.particle.particle_radius': 9.0,
                          'transitions.particle.swirl_order': 0,
                          'transitions.particle.swirl_strength': 1.0,
                          'transitions.particle.swirl_turns': 3.0,
                          'transitions.particle.texture_mapping': True,
                          'transitions.particle.trail_length': 0.15,
                          'transitions.particle.trail_strength': 0.6,
                          'transitions.particle.use_3d_shading': True,
                          'transitions.particle.wobble': True,
                          'transitions.pool.3D Block Spins': True,
                          'transitions.pool.Blinds': False,
                          'transitions.pool.Block Puzzle Flip': True,
                          'transitions.pool.Crossfade': False,
                          'transitions.pool.Crumble': True,
                          'transitions.pool.Diffuse': True,
                          'transitions.pool.Particle': True,
                          'transitions.pool.Ripple': True,
                          'transitions.pool.Slide': True,
                          'transitions.pool.Warp Dissolve': True,
                          'transitions.pool.Wipe': True,
                          'transitions.random_always': False,
                          'transitions.slide.direction': 'Random',
                          'transitions.type': 'Slide',
                          'transitions.wipe.direction': 'Random',
                          'widgets.abandonment_issues.bg_color': [35, 35, 35, 255],
                          'widgets.abandonment_issues.bg_opacity': 0.3,
                          'widgets.abandonment_issues.border_color': [255, 255, 255, 255],
                          'widgets.abandonment_issues.border_opacity': 1.0,
                          'widgets.abandonment_issues.color': [255, 255, 255, 230],
                          'widgets.abandonment_issues.enabled': False,
                          'widgets.abandonment_issues.font_family': 'Inter',
                          'widgets.abandonment_issues.font_size': 14,
                          'widgets.abandonment_issues.margin': 30,
                          'widgets.abandonment_issues.monitor': 'ALL',
                          'widgets.abandonment_issues.position': 'Bottom Right',
                          'widgets.abandonment_issues.preferred_height': 180,
                          'widgets.abandonment_issues.preferred_width': 420,
                          'widgets.abandonment_issues.show_background': True,
                          'widgets.achievement_pulse.artwork_shape': 'wide',
                          'widgets.achievement_pulse.bg_color': [35, 35, 35, 255],
                          'widgets.achievement_pulse.bg_opacity': 0.3,
                          'widgets.achievement_pulse.border_color': [255, 255, 255, 255],
                          'widgets.achievement_pulse.border_opacity': 1.0,
                          'widgets.achievement_pulse.capsule_border_color': [199, 213, 224, 145],
                          'widgets.achievement_pulse.capsule_fill_color': [199, 213, 224, 38],
                          'widgets.achievement_pulse.capsule_font_size': 12,
                          'widgets.achievement_pulse.color': [255, 255, 255, 230],
                          'widgets.achievement_pulse.custom_appid': None,
                          'widgets.achievement_pulse.double_capsules': True,
                          'widgets.achievement_pulse.enabled': False,
                          'widgets.achievement_pulse.font_family': 'Inter',
                          'widgets.achievement_pulse.font_size': 14,
                          'widgets.achievement_pulse.latest_unlock_count': 1,
                          'widgets.achievement_pulse.margin': 30,
                          'widgets.achievement_pulse.monitor': 'ALL',
                          'widgets.achievement_pulse.position': 'Middle Right',
                          'widgets.achievement_pulse.preferred_height': 290,
                          'widgets.achievement_pulse.preferred_width': 540,
                          'widgets.achievement_pulse.selection_mode': 'most_recent',
                          'widgets.achievement_pulse.show_artwork': True,
                          'widgets.achievement_pulse.show_background': True,
                          'widgets.achievement_pulse.show_latest': True,
                          'widgets.achievement_pulse.show_latest_achievement_artwork': True,
                          'widgets.achievement_pulse.show_playtime': True,
                          'widgets.achievement_pulse.show_previous': True,
                          'widgets.achievement_pulse.show_selected': False,
                          'widgets.achievement_pulse.show_source': False,
                          'widgets.achievement_pulse.show_total': True,
                          'widgets.achievement_pulse.square_artwork_size': 140,
                          'widgets.clock.analog_face_shadow': True,
                          'widgets.clock.bg_color': [35, 35, 35, 255],
                          'widgets.clock.bg_opacity': 0.6,
                          'widgets.clock.border_color': [255, 255, 255, 255],
                          'widgets.clock.border_opacity': 1.0,
                          'widgets.clock.calendar_font_size': 20,
                          'widgets.clock.calendar_layout': 'shared_line',
                          'widgets.clock.color': [255, 255, 255, 230],
                          'widgets.clock.display_mode': 'analog',
                          'widgets.clock.enabled': True,
                          'widgets.clock.font_family': 'Inter',
                          'widgets.clock.font_size': 78,
                          'widgets.clock.format': '24h',
                          'widgets.clock.margin': 30,
                          'widgets.clock.monitor': 'ALL',
                          'widgets.clock.position': 'Top Right',
                          'widgets.clock.show_background': False,
                          'widgets.clock.show_date': False,
                          'widgets.clock.show_day_of_week': False,
                          'widgets.clock.show_digital_separator': False,
                          'widgets.clock.show_numerals': True,
                          'widgets.clock.show_seconds': True,
                          'widgets.clock.show_timezone': True,
                          'widgets.clock.timezone': 'local',
                          'widgets.clock2.enabled': False,
                          'widgets.clock2.monitor': 2,
                          'widgets.clock2.timezone': 'local',
                          'widgets.clock3.enabled': False,
                          'widgets.clock3.monitor': 'ALL',
                          'widgets.clock3.timezone': 'local',
                          'widgets.friend_pulse.bg_color': [35, 35, 35, 255],
                          'widgets.friend_pulse.bg_opacity': 0.3,
                          'widgets.friend_pulse.border_color': [255, 255, 255, 255],
                          'widgets.friend_pulse.border_opacity': 1.0,
                          'widgets.friend_pulse.color': [255, 255, 255, 230],
                          'widgets.friend_pulse.enabled': False,
                          'widgets.friend_pulse.font_family': 'Inter',
                          'widgets.friend_pulse.font_size': 14,
                          'widgets.friend_pulse.margin': 30,
                          'widgets.friend_pulse.monitor': 'ALL',
                          'widgets.friend_pulse.position': 'Top Left',
                          'widgets.friend_pulse.preferred_height': 180,
                          'widgets.friend_pulse.preferred_width': 420,
                          'widgets.friend_pulse.show_background': True,
                          'widgets.media.artwork_size': 250,
                          'widgets.media.bg_color': [35, 35, 35, 255],
                          'widgets.media.bg_opacity': 0.6,
                          'widgets.media.border_color': [255, 255, 255, 255],
                          'widgets.media.border_opacity': 1.0,
                          'widgets.media.color': [255, 255, 255, 230],
                          'widgets.media.enabled': True,
                          'widgets.media.font_family': 'Inter',
                          'widgets.media.font_size': 22,
                          'widgets.media.margin': 30,
                          'widgets.media.monitor': '1',
                          'widgets.media.playback_progress_enabled': False,
                          'widgets.media.playback_progress_fill_color': [255, 255, 255, 230],
                          'widgets.media.playback_progress_glow_color': [255, 255, 255, 180],
                          'widgets.media.playback_progress_glow_enabled': False,
                          'widgets.media.playback_progress_height': 6,
                          'widgets.media.playback_progress_shadow_enabled': False,
                          'widgets.media.position': 'Bottom Left',
                          'widgets.media.provider': 'spotify',
                          'widgets.media.rounded_artwork_border': True,
                          'widgets.media.show_background': True,
                          'widgets.media.show_controls': True,
                          'widgets.media.show_header_frame': True,
                          'widgets.media.spotify_volume_enabled': True,
                          'widgets.media.spotify_volume_fill_color': [255, 255, 255, 230],
                          'widgets.reddit.bg_color': [35, 35, 35, 255],
                          'widgets.reddit.bg_opacity': 0.6,
                          'widgets.reddit.border_color': [255, 255, 255, 255],
                          'widgets.reddit.border_opacity': 1.0,
                          'widgets.reddit.color': [255, 255, 255, 230],
                          'widgets.reddit.enabled': True,
                          'widgets.reddit.exit_on_click': True,
                          'widgets.reddit.font_family': 'Inter',
                          'widgets.reddit.font_size': 14,
                          'widgets.reddit.limit': 10,
                          'widgets.reddit.margin': 30,
                          'widgets.reddit.monitor': 2,
                          'widgets.reddit.position': 'Bottom Right',
                          'widgets.reddit.provider': 'rss',
                          'widgets.reddit.show_background': True,
                          'widgets.reddit.show_separators': True,
                          'widgets.reddit.subreddit': 'All',
                          'widgets.reddit2.enabled': True,
                          'widgets.reddit2.limit': 20,
                          'widgets.reddit2.monitor': 2,
                          'widgets.reddit2.position': 'Bottom Center',
                          'widgets.reddit2.subreddit': 'Games',
                          'widgets.shadows.blur_radius': 18,
                          'widgets.shadows.color': [0, 0, 0, 255],
                          'widgets.shadows.enabled': True,
                          'widgets.shadows.frame_opacity': 0.77,
                          'widgets.shadows.header_enabled': True,
                          'widgets.shadows.offset': [4, 4],
                          'widgets.shadows.text_enabled': True,
                          'widgets.shadows.text_opacity': 0.33,
                          'widgets.spotify_visualizer.bubble_bar_border_color': [255,
                                                                                 255,
                                                                                 255,
                                                                                 255],
                          'widgets.spotify_visualizer.bubble_bar_border_opacity': 1.0,
                          'widgets.spotify_visualizer.bubble_bar_fill_color': [255, 255, 255, 230],
                          'widgets.spotify_visualizer.devcurve_bar_border_color': [255,
                                                                                   255,
                                                                                   255,
                                                                                   255],
                          'widgets.spotify_visualizer.devcurve_bar_border_opacity': 1.0,
                          'widgets.spotify_visualizer.devcurve_bar_fill_color': [255,
                                                                                 255,
                                                                                 255,
                                                                                 230],
                          'widgets.spotify_visualizer.enabled': True,
                          'widgets.spotify_visualizer.mode': 'bubble',
                          'widgets.spotify_visualizer.oscilloscope_bar_border_color': [255,
                                                                                       255,
                                                                                       255,
                                                                                       255],
                          'widgets.spotify_visualizer.oscilloscope_bar_border_opacity': 1.0,
                          'widgets.spotify_visualizer.oscilloscope_bar_fill_color': [255,
                                                                                     255,
                                                                                     255,
                                                                                     230],
                          'widgets.spotify_visualizer.sine_wave_bar_border_color': [255,
                                                                                    255,
                                                                                    255,
                                                                                    255],
                          'widgets.spotify_visualizer.sine_wave_bar_border_opacity': 1.0,
                          'widgets.spotify_visualizer.sine_wave_bar_fill_color': [255,
                                                                                  255,
                                                                                  255,
                                                                                  230],
                          'widgets.spotify_visualizer.spectrum_bar_border_color': [255,
                                                                                   255,
                                                                                   255,
                                                                                   255],
                          'widgets.spotify_visualizer.spectrum_bar_border_opacity': 1.0,
                          'widgets.spotify_visualizer.spectrum_bar_fill_color': [255,
                                                                                 255,
                                                                                 255,
                                                                                 230],
                          'widgets.steam.privacy_mode': 'Strict',
                          'widgets.steam.refresh_minutes': 10,
                          'widgets.steam.show_connection_info_icon': True,
                          'widgets.steam_progress.bg_color': [35, 35, 35, 255],
                          'widgets.steam_progress.bg_opacity': 0.3,
                          'widgets.steam_progress.border_color': [255, 255, 255, 255],
                          'widgets.steam_progress.border_opacity': 1.0,
                          'widgets.steam_progress.color': [255, 255, 255, 230],
                          'widgets.steam_progress.enabled': False,
                          'widgets.steam_progress.font_family': 'Inter',
                          'widgets.steam_progress.font_size': 14,
                          'widgets.steam_progress.margin': 30,
                          'widgets.steam_progress.monitor': 'ALL',
                          'widgets.steam_progress.position': 'Top Right',
                          'widgets.steam_progress.preferred_height': 180,
                          'widgets.steam_progress.preferred_width': 420,
                          'widgets.steam_progress.show_background': True,
                          'widgets.weather.bg_color': [35, 35, 35, 255],
                          'widgets.weather.bg_opacity': 0.3,
                          'widgets.weather.border_color': [255, 255, 255, 255],
                          'widgets.weather.border_opacity': 1.0,
                          'widgets.weather.color': [255, 255, 255, 230],
                          'widgets.weather.enabled': True,
                          'widgets.weather.font_family': 'Inter',
                          'widgets.weather.font_size': 28,
                          'widgets.weather.margin': 30,
                          'widgets.weather.monitor': 2,
                          'widgets.weather.position': 'Top Left',
                          'widgets.weather.show_background': True,
                          'widgets.weather.show_forecast': True},
 'display': {'gl_depth_bits': 24,
             'gl_stencil_bits': 8,
             'hw_accel': True,
             'mode': 'fill',
             'prefer_triple_buffer': True,
             'render_backend_mode': 'opengl',
             'same_image_all_monitors': False,
             'sharpen_downscale': False,
             'show_on_monitors': 'ALL',
             'use_lanczos': False},
 'input': {'halo_shape': 'cursor_light', 'interaction_mode': False},
 'mc': {},
 'preset': 'custom',
 'queue': {'shuffle': True},
 'sources': {'folders': [],
             'local_ratio': 55,
             'mode': 'folders',
             'rss_background_cap': 30,
             'rss_feeds': [],
             'rss_refresh_minutes': 10,
             'rss_rotating_cache_size': 20,
             'rss_save_directory': '',
             'rss_save_to_disk': False,
             'rss_stale_minutes': 60},
 'timing': {'interval': 40},
 'transitions': {'blinds': {'direction': 'Random', 'feather': 2},
                 'block_flip': {'cols': 24, 'direction': 'Random', 'rows': 24},
                 'blockspin': {'direction': 'Random'},
                 'burn': {'ash_density': 0.8,
                          'ash_enabled': True,
                          'char_width': 0.1,
                          'direction': 'Random',
                          'glow_color': [255, 162, 0, 255],
                          'glow_intensity': 1.0,
                          'jaggedness': 1.0,
                          'smoke_density': 0.8,
                          'smoke_enabled': True},
                 'crumble': {'crack_complexity': 1.0,
                             'piece_count': 16,
                             'weighting': 'Random Choice'},
                 'diffuse': {'block_size': 15, 'shape': 'Membrane'},
                 'direction': 'Random',
                 'duration_ms': 10524,
                 'durations': {'3D Block Spins': 9000,
                               'Blinds': 4000,
                               'Block Puzzle Flip': 5000,
                               'Burn': 8535,
                               'Crossfade': 5000,
                               'Crumble': 12000,
                               'Diffuse': 5500,
                               'Particle': 10524,
                               'Ripple': 7200,
                               'Slide': 5000,
                               'Warp Dissolve': 6000,
                               'Wipe': 4000},
                 'last_random_choice': 'Ripple',
                 'particle': {'direction': 'Random',
                              'gloss_size': 72.0,
                              'light_direction': 3,
                              'mode': 'Converge',
                              'overlap': 4.0,
                              'particle_radius': 8.000000000000004,
                              'swirl_order': 2,
                              'swirl_strength': 1.0,
                              'swirl_turns': 3.5000000000000004,
                              'texture_mapping': True,
                              'trail_length': 0.15,
                              'trail_strength': 0.6,
                              'use_3d_shading': True,
                              'wobble': True},
                 'pool': {'3D Block Spins': True,
                          'Blinds': False,
                          'Block Puzzle Flip': True,
                          'Burn': True,
                          'Crossfade': False,
                          'Crumble': True,
                          'Diffuse': True,
                          'Particle': True,
                          'Ripple': True,
                          'Slide': False,
                          'Warp Dissolve': True,
                          'Wipe': True},
                 'random_always': True,
                 'random_choice': 'Ripple',
                 'ripple': {'ripple_count': 3},
                 'slide': {'direction': 'Random'},
                 'type': '3D Block Spins',
                 'wipe': {'direction': 'Bottom to Top', 'last_direction': 'Bottom to Top'}},
 'ui': {'dialog_geometry': {'height': 758, 'width': 1362, 'x': 195, 'y': 57},
        'dialog_geometry.height': 900,
        'dialog_geometry.width': 1389,
        'dialog_geometry.x': 113,
        'dialog_geometry.y': 0,
        'gmail_bucket_states': {'appearance': True,
                                'backend': False,
                                'layout': False,
                                'separators': True},
        'last_tab_index': 5,
        'last_tab_scroll': {'accessibility': 0,
                            'display': 0,
                            'presets': 0,
                            'sources': 0,
                            'transitions': 0,
                            'widgets': 0},
        'last_tab_scroll.accessibility': 0,
        'last_tab_scroll.display': 0,
        'last_tab_scroll.presets': 0,
        'last_tab_scroll.sources': 85,
        'last_tab_scroll.transitions': 0,
        'last_tab_scroll.widgets': 230,
        'tab_state': {'widgets': {'view_state': {'scroll': 230,
                                                 'subtab': 3,
                                                 'subtab_id': 'visualizers',
                                                 'subtab_scrolls': {'0': 0,
                                                                    '1': 0,
                                                                    '2': 0,
                                                                    '3': 0,
                                                                    '4': 0,
                                                                    '5': 0,
                                                                    '6': 0,
                                                                    '7': 0}}}},
        'tab_state.widgets.view_state.scroll': 230,
        'tab_state.widgets.view_state.subtab': 2,
        'visualizer_adv_states': {'bubble': False,
                                  'devcurve': False,
                                  'oscilloscope': False,
                                  'sine_wave': False,
                                  'spectrum': False},
        'visualizer_bucket_states': {'bubble:appearance': True,
                                     'bubble:bounce': True,
                                     'bubble:ghost': False,
                                     'bubble:layout': False,
                                     'bubble:motion': True,
                                     'bubble:population': False,
                                     'bubble:reactivity': False,
                                     'devcurve:core': True,
                                     'devcurve:foreground_fx': False,
                                     'devcurve:ghost': False,
                                     'devcurve:shaper': True,
                                     'oscilloscope:appearance': True,
                                     'oscilloscope:behavior': True,
                                     'oscilloscope:layout': False,
                                     'oscilloscope:multi_line': False,
                                     'sine_wave:appearance': True,
                                     'sine_wave:layout': False,
                                     'sine_wave:motion': True,
                                     'sine_wave:multi_line': False,
                                     'sine_wave:response': True,
                                     'spectrum:appearance': True,
                                     'spectrum:audio': True,
                                     'spectrum:ghost': True,
                                     'spectrum:render': True,
                                     'spectrum:shape': True},
        'visualizer_scroll_positions': {'bubble': 0},
        'visualizer_tech_bucket_states': {'bubble:agc': False,
                                          'bubble:transient': True,
                                          'devcurve:agc': False,
                                          'devcurve:transient': True,
                                          'oscilloscope:agc': False,
                                          'oscilloscope:transient': True,
                                          'sine_wave:agc': False,
                                          'sine_wave:transient': True,
                                          'spectrum:agc': False,
                                          'spectrum:transient': True},
        'visualizer_tech_states': {'bubble': True,
                                   'devcurve': True,
                                   'oscilloscope': True,
                                   'sine_wave': True,
                                   'spectrum': True},
        'widget_bucket_states': {'clock:layout': False,
                                 'clock:time': True,
                                 'defaults:appearance': True,
                                 'defaults:cache': True,
                                 'defaults:layout': True,
                                 'media:appearance': True,
                                 'media:controls': True,
                                 'media:provider_layout': True,
                                 'reddit:interaction': False,
                                 'reddit:reddit1': False,
                                 'reddit:shared_appearance': False,
                                 'reddit:shared_layout': False,
                                 'steam:abandonment_issues': True,
                                 'steam:abandonment_issues_appearance': True,
                                 'steam:abandonment_issues_content': True,
                                 'steam:abandonment_issues_layout': True,
                                 'steam:achievement_pulse': True,
                                 'steam:achievement_pulse_appearance': True,
                                 'steam:achievement_pulse_content': True,
                                 'steam:achievement_pulse_layout': True,
                                 'steam:connection': True,
                                 'weather:content': True,
                                 'weather:source_layout': True}},
 'visualizer_custom_presets': {'bubble.bubble_adaptive_sensitivity': False,
                               'bubble.bubble_agc_strength': 0.0,
                               'bubble.bubble_audio_block_size': 128,
                               'bubble.bubble_bar_border_color': [255, 255, 255, 255],
                               'bubble.bubble_bar_border_opacity': 1.0,
                               'bubble.bubble_bar_count': 48,
                               'bubble.bubble_bar_fill_color': [12, 12, 12, 230],
                               'bubble.bubble_big_bass_pulse': 0.67,
                               'bubble.bubble_big_contraction_bias': 0.4,
                               'bubble.bubble_big_count': 5,
                               'bubble.bubble_big_size_clamp': 2.96,
                               'bubble.bubble_big_size_max': 0.037,
                               'bubble.bubble_big_specular_max_size': 4.03,
                               'bubble.bubble_big_visual_smoothing': 1.0,
                               'bubble.bubble_bounce_big_pct': 0,
                               'bubble.bubble_bounce_big_speed': 0.0,
                               'bubble.bubble_bounce_same_only': True,
                               'bubble.bubble_bounce_small_pct': 60,
                               'bubble.bubble_bounce_small_speed': 0.1,
                               'bubble.bubble_collision_pop_mode': 'one',
                               'bubble.bubble_drift_amount': 0.35,
                               'bubble.bubble_drift_direction': 'swish_horizontal',
                               'bubble.bubble_drift_frequency': 0.5,
                               'bubble.bubble_drift_speed': 0.15,
                               'bubble.bubble_dynamic_floor': False,
                               'bubble.bubble_dynamic_range_enabled': False,
                               'bubble.bubble_ghost_alpha': 0.15,
                               'bubble.bubble_ghost_decay': 0.5,
                               'bubble.bubble_ghosting_enabled': True,
                               'bubble.bubble_gradient_dark': [0, 16, 45, 255],
                               'bubble.bubble_gradient_direction': 'top',
                               'bubble.bubble_gradient_light': [0, 82, 175, 255],
                               'bubble.bubble_gradient_semantics_version': 2,
                               'bubble.bubble_group_drift': False,
                               'bubble.bubble_growth': 5.0,
                               'bubble.bubble_input_gain': 0.75,
                               'bubble.bubble_kick_lane_gain': 1.0,
                               'bubble.bubble_manual_floor': 0.3,
                               'bubble.bubble_outline_color': [219, 239, 255, 255],
                               'bubble.bubble_pop_color': [38, 115, 191, 255],
                               'bubble.bubble_rainbow_enabled': False,
                               'bubble.bubble_rainbow_speed': 0.15,
                               'bubble.bubble_rotation_amount': 0.0,
                               'bubble.bubble_sensitivity': 0.55,
                               'bubble.bubble_small_count': 44,
                               'bubble.bubble_small_freq_pulse': 1.1,
                               'bubble.bubble_small_size_max': 0.01,
                               'bubble.bubble_specular_color': [219, 239, 255, 255],
                               'bubble.bubble_specular_direction': 'top_left',
                               'bubble.bubble_stream_constant_speed': 0.15,
                               'bubble.bubble_stream_direction': 'up',
                               'bubble.bubble_stream_reactivity': 1.35,
                               'bubble.bubble_stream_speed_cap': 1.95,
                               'bubble.bubble_surface_reach': 1.0,
                               'bubble.bubble_tail_opacity': 0.8,
                               'bubble.bubble_trail_strength': 0.8,
                               'bubble.bubble_transient_clamp': 1.15,
                               'bubble.bubble_transient_mix_bass': 0.2,
                               'bubble.bubble_transient_mix_vocal': 0.15,
                               'bubble.bubble_transient_pulse_gain': 0.05,
                               'bubble.mode': 'bubble',
                               'bubble.monitor': '2'},
 'widgets': {'abandonment_issues': {'accent_color': [211, 209, 222, 225],
                                    'artwork_shape': 'portrait',
                                    'artwork_size': 140,
                                    'bg_color': [35, 35, 35, 255],
                                    'bg_opacity': 0.3,
                                    'border_color': [255, 255, 255, 255],
                                    'border_opacity': 1.0,
                                    'color': [255, 255, 255, 230],
                                    'enabled': False,
                                    'font_family': 'Inter',
                                    'font_size': 14,
                                    'guilt_desaturater': False,
                                    'guilt_desaturation_strength': 55,
                                    'margin': 30,
                                    'minimum_inactivity_weeks': 12,
                                    'minimum_playtime_minutes': 15,
                                    'monitor': '1',
                                    'never_show_appids': [],
                                    'pinned_appid': None,
                                    'position': 'Bottom Right',
                                    'preferred_height': 331,
                                    'preferred_max_playtime_hours': 2,
                                    'preferred_max_unlocked_achievements': 2,
                                    'preferred_minimum_inactivity_weeks': 26,
                                    'preferred_width': 600,
                                    'selection_mode': 'smart_rotation',
                                    'show_achievements': True,
                                    'show_archive_class': False,
                                    'show_artwork': True,
                                    'show_background': True,
                                    'show_last_played': True,
                                    'show_last_unlock': True,
                                    'show_pinned': False,
                                    'show_playtime': True,
                                    'show_queue': False,
                                    'show_rediscovery_message': True,
                                    'show_source': False},
             'achievement_pulse': {'artwork_shape': 'portrait',
                                   'bg_color': [35, 35, 35, 255],
                                   'bg_opacity': 0.3,
                                   'border_color': [255, 255, 255, 255],
                                   'border_opacity': 1.0,
                                   'capsule_border_color': [227, 243, 255, 200],
                                   'capsule_fill_color': [199, 213, 224, 38],
                                   'capsule_font_size': 12,
                                   'color': [255, 255, 255, 230],
                                   'custom_appid': None,
                                   'double_capsules': True,
                                   'enabled': False,
                                   'font_family': 'Inter',
                                   'font_size': 15,
                                   'latest_unlock_count': 5,
                                   'margin': 30,
                                   'monitor': '1',
                                   'position': 'Bottom Left',
                                   'preferred_height': 334,
                                   'preferred_width': 600,
                                   'selection_mode': 'most_recent',
                                   'show_artwork': True,
                                   'show_background': True,
                                   'show_latest': True,
                                   'show_latest_achievement_artwork': True,
                                   'show_playtime': True,
                                   'show_previous': True,
                                   'show_selected': False,
                                   'show_source': False,
                                   'show_total': True,
                                   'square_artwork_size': 140},
             'clock': {'analog_face_shadow': True,
                       'bg_color': [35, 35, 35, 255],
                       'bg_opacity': 0.3,
                       'border_color': [255, 255, 255, 255],
                       'border_opacity': 1.0,
                       'calendar_font_size': 22,
                       'calendar_layout': 'shared_line',
                       'color': [255, 255, 255, 230],
                       'display_mode': 'analog',
                       'enabled': True,
                       'font_family': 'Inter',
                       'font_size': 78,
                       'format': '24h',
                       'margin': 30,
                       'monitor': 'ALL',
                       'position': 'Top Right',
                       'shared_tick': True,
                       'show_background': False,
                       'show_date': False,
                       'show_day_of_week': True,
                       'show_digital_separator': False,
                       'show_numerals': True,
                       'show_seconds': True,
                       'show_timezone': True,
                       'timezone': 'local'},
             'clock2': {'color': [255, 255, 255, 230],
                        'display_mode': 'digital',
                        'enabled': False,
                        'font_family': 'Inter',
                        'font_size': 32,
                        'format': '24h',
                        'margin': 30,
                        'monitor': 2,
                        'position': 'Bottom Right',
                        'show_numerals': True,
                        'show_seconds': False,
                        'show_timezone': True,
                        'timezone': 'local'},
             'clock3': {'color': [255, 255, 255, 230],
                        'display_mode': 'digital',
                        'enabled': False,
                        'font_family': 'Inter',
                        'font_size': 32,
                        'format': '24h',
                        'margin': 30,
                        'monitor': 'ALL',
                        'position': 'Bottom Left',
                        'show_numerals': True,
                        'show_seconds': False,
                        'show_timezone': True,
                        'timezone': 'local'},
             'custom_layout': {'displays': {}, 'version': 1},
             'custom_layout_restore': {'version': 1,
                                       'widgets': {'abandonment_issues': {'monitor': '1',
                                                                          'position': 'Bottom '
                                                                                      'Right'},
                                                   'achievement_pulse': {'monitor': '1',
                                                                         'position': 'Bottom Left'},
                                                   'clock': {'monitor': 'ALL',
                                                             'position': 'Top Right'},
                                                   'clock2': {'monitor': '2',
                                                              'position': 'Top Right'},
                                                   'clock3': {'monitor': 'ALL',
                                                              'position': 'Top Right'},
                                                   'gmail': {'monitor': '2',
                                                             'position': 'Bottom Left'},
                                                   'media': {'monitor': '2',
                                                             'position': 'Top Left'},
                                                   'reddit': {'monitor': '2',
                                                              'position': 'Bottom Center'},
                                                   'reddit2': {'monitor': '2',
                                                               'position': 'Bottom Right'},
                                                   'spotify_visualizer': {'monitor': '2',
                                                                          'position': 'Top Left'},
                                                   'weather': {'monitor': '1',
                                                               'position': 'Bottom Right'}}},
             'friend_pulse': {'bg_color': [35, 35, 35, 255],
                              'bg_opacity': 0.3,
                              'border_color': [255, 255, 255, 255],
                              'border_opacity': 1.0,
                              'color': [255, 255, 255, 230],
                              'enabled': False,
                              'font_family': 'Inter',
                              'font_size': 14,
                              'margin': 30,
                              'monitor': 'ALL',
                              'position': 'Top Left',
                              'preferred_height': 180,
                              'preferred_width': 420,
                              'show_background': True},
             'global': {'card_border_width_px': 4, 'stacking_enabled': True},
             'gmail': {'account_slot': '0',
                       'auto_title_case': True,
                       'bg_color': [35, 35, 35, 255],
                       'bg_opacity': 0.3,
                       'border_color': [255, 255, 255, 255],
                       'border_opacity': 1.0,
                       'boundary_separator_color': [180, 180, 180, 80],
                       'boundary_separator_thickness': 3,
                       'clean_sender_names': True,
                       'color': [255, 255, 255, 230],
                       'date_display_mode': 'numeric',
                       'desaturate_when_no_unread': False,
                       'enabled': True,
                       'filter_label': 'INBOX',
                       'font_family': 'Inter',
                       'font_size': 12,
                       'group_threads': True,
                       'header_logo_px_adjust': 2,
                       'limit': 10,
                       'margin': 30,
                       'max_sender_words': 3,
                       'max_subject_words': 4,
                       'monitor': 2,
                       'play_sound_on_new_mail': False,
                       'position': 'Bottom Left',
                       'refresh_minutes': 5,
                       'sender_subject_ratio': 35,
                       'separator_color': [200, 200, 200, 40],
                       'separator_thickness': 3,
                       'show_background': True,
                       'show_envelope_icon': False,
                       'show_header_border': True,
                       'show_refresh_spiral': True,
                       'show_sender': True,
                       'show_separators': True,
                       'show_subject': True,
                       'show_three_dot_menu': True,
                       'show_timestamp': True,
                       'show_unread_count_in_header': True,
                       'sound_file_path': 'resources/tutuogg.ogg',
                       'sound_volume_percent': 25,
                       'width': 600},
             'imgur': {'bg_color': [35, 35, 35, 255],
                       'bg_opacity': 0.3,
                       'border_color': [255, 255, 255, 255],
                       'border_opacity': 1.0,
                       'click_opens_browser': True,
                       'color': [255, 255, 255, 230],
                       'custom_tag': '',
                       'enabled': False,
                       'font_family': 'Inter',
                       'font_size': 11,
                       'grid_columns': 4,
                       'grid_rows': 2,
                       'header_font_size': 14,
                       'image_border_color': [255, 255, 255, 255],
                       'image_border_enabled': True,
                       'image_border_radius': 4,
                       'image_border_width': 2,
                       'image_spacing': 4,
                       'layout_mode': 'hybrid',
                       'margin': 30,
                       'monitor': 2,
                       'position': 'Top Right',
                       'show_background': True,
                       'show_header': True,
                       'tag': 'most_viral',
                       'update_interval': 600},
             'layout_slots': {'slots': {}, 'version': 1},
             'media': {'artwork_size': 250,
                       'bg_color': [35, 35, 35, 255],
                       'bg_opacity': 0.3,
                       'border_color': [255, 255, 255, 255],
                       'border_opacity': 1.0,
                       'color': [255, 255, 255, 230],
                       'enabled': True,
                       'font_family': 'Inter',
                       'font_size': 17,
                       'margin': 30,
                       'monitor': 2,
                       'mute_button_enabled': False,
                       'playback_progress_enabled': False,
                       'playback_progress_fill_color': [255, 255, 255, 230],
                       'playback_progress_glow_color': [255, 255, 255, 180],
                       'playback_progress_glow_enabled': False,
                       'playback_progress_height': 6,
                       'playback_progress_shadow_enabled': False,
                       'position': 'Top Left',
                       'provider': 'spotify',
                       'rounded_artwork_border': True,
                       'show_background': True,
                       'show_controls': True,
                       'show_header_frame': True,
                       'spotify_volume_enabled': True,
                       'spotify_volume_fill_color': [79, 79, 79, 150]},
             'reddit': {'bg_color': [35, 35, 35, 255],
                        'bg_opacity': 0.3,
                        'border_color': [255, 255, 255, 255],
                        'border_opacity': 1.0,
                        'color': [255, 255, 255, 230],
                        'enabled': True,
                        'exit_on_click': True,
                        'font_family': 'Inter',
                        'font_size': 14,
                        'header_logo_px_adjust': 0,
                        'limit': 20,
                        'margin': 30,
                        'monitor': 2,
                        'position': 'Bottom Center',
                        'provider': 'rss',
                        'show_background': True,
                        'show_refresh_spiral': True,
                        'show_separators': True,
                        'subreddit': 'All'},
             'reddit2': {'bg_color': [35, 35, 35, 255],
                         'bg_opacity': 0.3,
                         'border_color': [255, 255, 255, 255],
                         'border_opacity': 1.0,
                         'color': [255, 255, 255, 230],
                         'enabled': True,
                         'limit': 20,
                         'monitor': 2,
                         'position': 'Bottom Right',
                         'show_background': True,
                         'subreddit': 'Games'},
             'shadows': {'blur_radius': 18,
                         'color': [0, 0, 0, 255],
                         'enabled': True,
                         'frame_opacity': 0.77,
                         'header_enabled': True,
                         'offset': [4, 4],
                         'text_enabled': True,
                         'text_opacity': 0.33},
             'spotify_visualizer': {'bubble_adaptive_sensitivity': False,
                                    'bubble_agc_strength': 0.0,
                                    'bubble_audio_block_size': 128,
                                    'bubble_bar_border_color': [255, 255, 255, 255],
                                    'bubble_bar_border_opacity': 1.0,
                                    'bubble_bar_count': 48,
                                    'bubble_bar_fill_color': [12, 12, 12, 230],
                                    'bubble_big_bass_pulse': 0.67,
                                    'bubble_big_contraction_bias': 0.4,
                                    'bubble_big_count': 5,
                                    'bubble_big_size_clamp': 2.96,
                                    'bubble_big_size_max': 0.037,
                                    'bubble_big_specular_max_size': 4.03,
                                    'bubble_big_visual_smoothing': 1.0,
                                    'bubble_bounce_big_pct': 0,
                                    'bubble_bounce_big_speed': 0.0,
                                    'bubble_bounce_same_only': True,
                                    'bubble_bounce_small_pct': 60,
                                    'bubble_bounce_small_speed': 0.1,
                                    'bubble_collision_pop_mode': 'one',
                                    'bubble_drift_amount': 0.35,
                                    'bubble_drift_direction': 'swish_horizontal',
                                    'bubble_drift_frequency': 0.5,
                                    'bubble_drift_speed': 0.15,
                                    'bubble_dynamic_floor': False,
                                    'bubble_dynamic_range_enabled': False,
                                    'bubble_ghost_alpha': 0.15,
                                    'bubble_ghost_decay': 0.5,
                                    'bubble_ghosting_enabled': True,
                                    'bubble_gradient_dark': [0, 4, 11, 255],
                                    'bubble_gradient_direction': 'top',
                                    'bubble_gradient_light': [43, 61, 80, 255],
                                    'bubble_gradient_semantics_version': 2,
                                    'bubble_group_drift': False,
                                    'bubble_growth': 5.0,
                                    'bubble_input_gain': 0.75,
                                    'bubble_kick_lane_gain': 1.0,
                                    'bubble_manual_floor': 0.3,
                                    'bubble_outline_color': [243, 250, 255, 245],
                                    'bubble_pop_color': [138, 146, 191, 255],
                                    'bubble_rainbow_enabled': False,
                                    'bubble_rainbow_speed': 0.15,
                                    'bubble_rotation_amount': 0.0,
                                    'bubble_sensitivity': 0.55,
                                    'bubble_small_count': 44,
                                    'bubble_small_freq_pulse': 1.1,
                                    'bubble_small_size_max': 0.01,
                                    'bubble_specular_color': [255, 255, 255, 235],
                                    'bubble_specular_direction': 'top_left',
                                    'bubble_stream_constant_speed': 0.15,
                                    'bubble_stream_direction': 'up',
                                    'bubble_stream_reactivity': 1.35,
                                    'bubble_stream_speed_cap': 1.95,
                                    'bubble_surface_reach': 1.0,
                                    'bubble_tail_opacity': 0.8,
                                    'bubble_trail_strength': 0.8,
                                    'bubble_transient_clamp': 1.15,
                                    'bubble_transient_mix_bass': 0.2,
                                    'bubble_transient_mix_vocal': 0.15,
                                    'bubble_transient_pulse_gain': 0.05,
                                    'devcurve_active_layer': 'bass',
                                    'devcurve_adaptive_sensitivity': True,
                                    'devcurve_agc_strength': 0.5,
                                    'devcurve_audio_block_size': 0,
                                    'devcurve_bar_border_color': [255, 255, 255, 255],
                                    'devcurve_bar_border_opacity': 1.0,
                                    'devcurve_bar_count': 32,
                                    'devcurve_bar_fill_color': [255, 255, 255, 230],
                                    'devcurve_base_level': 0.58,
                                    'devcurve_dynamic_floor': True,
                                    'devcurve_dynamic_range_enabled': False,
                                    'devcurve_foreground_shadow_alpha': 0.36,
                                    'devcurve_foreground_shadow_darken': 0.42,
                                    'devcurve_foreground_shadow_enabled': False,
                                    'devcurve_foreground_shadow_offset': 0.1,
                                    'devcurve_foreground_specular_alpha': 0.78,
                                    'devcurve_foreground_specular_crest_bias': 1.05,
                                    'devcurve_foreground_specular_enabled': False,
                                    'devcurve_foreground_specular_offset': 0.028,
                                    'devcurve_foreground_specular_width': 0.022,
                                    'devcurve_ghost_alpha': 0.0,
                                    'devcurve_ghost_decay': 0.4,
                                    'devcurve_ghosting_enabled': False,
                                    'devcurve_growth': 3.0,
                                    'devcurve_idle_motion': 0.2,
                                    'devcurve_idle_speed': 0.6,
                                    'devcurve_input_gain': 1.0,
                                    'devcurve_kick_lane_gain': 1.0,
                                    'devcurve_layer_bass_alpha': 0.55,
                                    'devcurve_layer_bass_color': [82, 167, 255, 230],
                                    'devcurve_layer_bass_enabled': True,
                                    'devcurve_layer_bass_offset': 0.0,
                                    'devcurve_layer_bass_order': 1,
                                    'devcurve_layer_bass_outline_color': [255, 255, 255, 255],
                                    'devcurve_layer_bass_outline_width': 0.006,
                                    'devcurve_layer_bass_power': 1.0,
                                    'devcurve_layer_bass_shape_nodes': [[0.0, 0.58],
                                                                        [0.35, 0.64],
                                                                        [0.7, 0.52],
                                                                        [1.0, 0.6]],
                                    'devcurve_layer_mids_alpha': 0.46,
                                    'devcurve_layer_mids_color': [100, 145, 255, 220],
                                    'devcurve_layer_mids_enabled': True,
                                    'devcurve_layer_mids_offset': 0.01,
                                    'devcurve_layer_mids_order': 3,
                                    'devcurve_layer_mids_outline_color': [255, 255, 255, 255],
                                    'devcurve_layer_mids_outline_width': 0.006,
                                    'devcurve_layer_mids_power': 1.0,
                                    'devcurve_layer_mids_shape_nodes': [[0.0, 0.58],
                                                                        [0.35, 0.64],
                                                                        [0.7, 0.52],
                                                                        [1.0, 0.6]],
                                    'devcurve_layer_transients_alpha': 0.66,
                                    'devcurve_layer_transients_color': [215, 240, 255, 240],
                                    'devcurve_layer_transients_enabled': True,
                                    'devcurve_layer_transients_offset': 0.0,
                                    'devcurve_layer_transients_order': 4,
                                    'devcurve_layer_transients_outline_color': [255, 255, 255, 255],
                                    'devcurve_layer_transients_outline_width': 0.006,
                                    'devcurve_layer_transients_power': 1.15,
                                    'devcurve_layer_transients_shape_nodes': [[0.0, 0.58],
                                                                              [0.35, 0.64],
                                                                              [0.7, 0.52],
                                                                              [1.0, 0.6]],
                                    'devcurve_layer_vocals_alpha': 0.42,
                                    'devcurve_layer_vocals_color': [136, 190, 255, 220],
                                    'devcurve_layer_vocals_enabled': True,
                                    'devcurve_layer_vocals_offset': -0.01,
                                    'devcurve_layer_vocals_order': 2,
                                    'devcurve_layer_vocals_outline_color': [255, 255, 255, 255],
                                    'devcurve_layer_vocals_outline_width': 0.006,
                                    'devcurve_layer_vocals_power': 1.0,
                                    'devcurve_layer_vocals_shape_nodes': [[0.0, 0.58],
                                                                          [0.35, 0.64],
                                                                          [0.7, 0.52],
                                                                          [1.0, 0.6]],
                                    'devcurve_manual_floor': 0.12,
                                    'devcurve_motion_power': 1.0,
                                    'devcurve_rainbow_enabled': False,
                                    'devcurve_rainbow_speed': 0.5,
                                    'devcurve_sensitivity': 1.0,
                                    'devcurve_smoothness': 0.55,
                                    'devcurve_transient_clamp': 1.5,
                                    'devcurve_transient_pulse_gain': 1.0,
                                    'enabled': True,
                                    'mode': 'devcurve',
                                    'monitor': 'ALL',
                                    'osc_ghost_decay': 0.4,
                                    'osc_ghost_intensity': 0.4,
                                    'osc_ghost_line2_enabled': True,
                                    'osc_ghost_line3_enabled': True,
                                    'osc_ghost_line4_enabled': True,
                                    'osc_ghost_line5_enabled': True,
                                    'osc_ghost_line6_enabled': True,
                                    'osc_ghosting_enabled': True,
                                    'osc_glow_color': [255, 255, 255, 255],
                                    'osc_glow_enabled': True,
                                    'osc_glow_intensity': 0.6,
                                    'osc_glow_reactivity': 1.0,
                                    'osc_glow_size': 1.0,
                                    'osc_growth': 3.01,
                                    'osc_line2_color': [21, 21, 21, 255],
                                    'osc_line2_glow_color': [255, 255, 255, 230],
                                    'osc_line3_color': [21, 21, 21, 250],
                                    'osc_line3_glow_color': [255, 255, 255, 240],
                                    'osc_line4_color': [255, 0, 150, 230],
                                    'osc_line4_glow_color': [255, 0, 150, 180],
                                    'osc_line5_color': [0, 255, 200, 230],
                                    'osc_line5_glow_color': [0, 255, 200, 180],
                                    'osc_line6_color': [200, 100, 255, 230],
                                    'osc_line6_glow_color': [200, 100, 255, 180],
                                    'osc_line_amplitude': 4.7,
                                    'osc_line_color': [0, 0, 0, 255],
                                    'osc_line_count': 1,
                                    'osc_line_dim': False,
                                    'osc_line_offset_bias': 0.0,
                                    'osc_reactive_glow': True,
                                    'osc_smoothing': 0.6,
                                    'osc_speed': 0.33,
                                    'osc_vertical_shift': 25,
                                    'oscilloscope_adaptive_sensitivity': True,
                                    'oscilloscope_agc_strength': 0.5,
                                    'oscilloscope_audio_block_size': 512,
                                    'oscilloscope_bar_border_color': [255, 255, 255, 255],
                                    'oscilloscope_bar_border_opacity': 1.0,
                                    'oscilloscope_bar_count': 32,
                                    'oscilloscope_bar_fill_color': [255, 255, 255, 230],
                                    'oscilloscope_dynamic_floor': True,
                                    'oscilloscope_dynamic_range_enabled': False,
                                    'oscilloscope_input_gain': 1.0,
                                    'oscilloscope_kick_lane_gain': 1.0,
                                    'oscilloscope_manual_floor': 0.12,
                                    'oscilloscope_rainbow_enabled': False,
                                    'oscilloscope_rainbow_speed': 0.5,
                                    'oscilloscope_sensitivity': 0.4,
                                    'oscilloscope_transient_clamp': 1.5,
                                    'oscilloscope_transient_pulse_gain': 1.0,
                                    'oscilloscope_transient_width_mix': 0.35,
                                    'position': 'Bottom Left',
                                    'preset_bubble': 0,
                                    'preset_devcurve': 0,
                                    'preset_oscilloscope': 0,
                                    'preset_sine_wave': 4,
                                    'preset_spectrum': 0,
                                    'rainbow_enabled': False,
                                    'rainbow_speed': 0.5,
                                    'sine_card_adaptation': 0.24,
                                    'sine_crawl_amount': 0.0,
                                    'sine_density': 1.6,
                                    'sine_displacement': 0.0,
                                    'sine_ghost_alpha': 0.12,
                                    'sine_ghost_decay': 0.68,
                                    'sine_ghost_line2_enabled': True,
                                    'sine_ghost_line3_enabled': True,
                                    'sine_ghost_line4_enabled': True,
                                    'sine_ghost_line5_enabled': True,
                                    'sine_ghost_line6_enabled': True,
                                    'sine_ghosting_enabled': True,
                                    'sine_glow_color': [148, 188, 255, 218],
                                    'sine_glow_enabled': True,
                                    'sine_glow_intensity': 0.42,
                                    'sine_glow_reactivity': 1.3,
                                    'sine_glow_size': 1.0,
                                    'sine_heartbeat': 0.0,
                                    'sine_line1_color': [255, 255, 255, 230],
                                    'sine_line1_shift': 0.0,
                                    'sine_line2_color': [192, 224, 255, 198],
                                    'sine_line2_glow_color': [160, 178, 255, 178],
                                    'sine_line2_shift': 0.22,
                                    'sine_line3_color': [230, 196, 255, 190],
                                    'sine_line3_glow_color': [202, 148, 255, 172],
                                    'sine_line3_shift': -0.22,
                                    'sine_line4_color': [255, 120, 50, 230],
                                    'sine_line4_glow_color': [255, 120, 50, 180],
                                    'sine_line4_shift': 0.0,
                                    'sine_line5_color': [50, 255, 120, 230],
                                    'sine_line5_glow_color': [50, 255, 120, 180],
                                    'sine_line5_shift': 0.0,
                                    'sine_line6_color': [255, 0, 150, 230],
                                    'sine_line6_glow_color': [255, 0, 150, 180],
                                    'sine_line6_shift': 0.0,
                                    'sine_line_color': [255, 255, 255, 228],
                                    'sine_line_count': 3,
                                    'sine_line_dim': False,
                                    'sine_line_offset_bias': 0.12,
                                    'sine_micro_wobble': 0.08,
                                    'sine_reactive_glow': True,
                                    'sine_sensitivity': 0.36,
                                    'sine_smoothing': 0.7,
                                    'sine_speed': 0.42,
                                    'sine_travel_line2': 0,
                                    'sine_travel_line3': 0,
                                    'sine_travel_line4': 0,
                                    'sine_travel_line5': 0,
                                    'sine_travel_line6': 0,
                                    'sine_vertical_shift': 44,
                                    'sine_wave_adaptive_sensitivity': True,
                                    'sine_wave_agc_strength': 0.62,
                                    'sine_wave_audio_block_size': 256,
                                    'sine_wave_bar_border_color': [255, 255, 255, 255],
                                    'sine_wave_bar_border_opacity': 1.0,
                                    'sine_wave_bar_count': 40,
                                    'sine_wave_bar_fill_color': [0, 0, 0, 130],
                                    'sine_wave_dynamic_floor': True,
                                    'sine_wave_dynamic_range_enabled': False,
                                    'sine_wave_effect': 0.3,
                                    'sine_wave_growth': 4.0,
                                    'sine_wave_input_gain': 0.44,
                                    'sine_wave_kick_lane_gain': 0.85,
                                    'sine_wave_manual_floor': 0.12,
                                    'sine_wave_rainbow_enabled': False,
                                    'sine_wave_rainbow_speed': 0.22,
                                    'sine_wave_sensitivity': 0.36,
                                    'sine_wave_transient_clamp': 1.0,
                                    'sine_wave_transient_pulse_gain': 1.0,
                                    'sine_wave_transient_width_mix': 0.32,
                                    'sine_wave_travel': 2,
                                    'sine_width_reaction': 0.18,
                                    'spectrum_adaptive_sensitivity': True,
                                    'spectrum_agc_strength': 0.5,
                                    'spectrum_audio_block_size': 512,
                                    'spectrum_bar_border_color': [255, 255, 255, 255],
                                    'spectrum_bar_border_opacity': 1.0,
                                    'spectrum_bar_count': 33,
                                    'spectrum_bar_fill_color': [12, 12, 12, 230],
                                    'spectrum_border_radius': 2.0,
                                    'spectrum_drop_speed': 1.0,
                                    'spectrum_dynamic_floor': True,
                                    'spectrum_dynamic_range_enabled': False,
                                    'spectrum_ghost_alpha': 0.4,
                                    'spectrum_ghost_decay': 0.35,
                                    'spectrum_ghosting_enabled': True,
                                    'spectrum_glow_color': [110, 220, 255, 235],
                                    'spectrum_glow_enabled': False,
                                    'spectrum_glow_intensity': 0.55,
                                    'spectrum_growth': 3.96,
                                    'spectrum_input_gain': 1.0,
                                    'spectrum_kick_lane_gain': 1.0,
                                    'spectrum_lane_strengths_linear': {'Bass': 0.8,
                                                                       'Hi-Mid': 0.8,
                                                                       'Low-Mid': 0.7,
                                                                       'Treble': 1.0,
                                                                       'Vocal': 0.64},
                                    'spectrum_lane_strengths_mirrored': {'Bass': 0.8,
                                                                         'Low-Mid': 0.7,
                                                                         'Mid': 0.6,
                                                                         'Vocal': 0.64},
                                    'spectrum_lane_transient_mix': 0.65,
                                    'spectrum_link_fill_border': False,
                                    'spectrum_manual_floor': 0.12,
                                    'spectrum_mirrored': True,
                                    'spectrum_notch_positions_linear': [[0.0, 'Bass'],
                                                                        [0.24, 'Low-Mid'],
                                                                        [0.46, 'Vocal'],
                                                                        [0.72, 'Hi-Mid'],
                                                                        [1.0, 'Treble']],
                                    'spectrum_notch_positions_mirrored': [[0.0, 'Mid'],
                                                                          [0.3, 'Vocal'],
                                                                          [0.65, 'Low-Mid'],
                                                                          [1.0, 'Bass']],
                                    'spectrum_profile_floor': 0.12,
                                    'spectrum_rainbow_border': False,
                                    'spectrum_rainbow_enabled': False,
                                    'spectrum_rainbow_speed': 0.5,
                                    'spectrum_render_mode': 'bars',
                                    'spectrum_sensitivity': 0.4,
                                    'spectrum_shape_nodes': [[0.0, 0.4],
                                                             [0.35, 0.75],
                                                             [0.65, 0.55],
                                                             [1.0, 0.8]],
                                    'spectrum_transient_clamp': 1.5,
                                    'spectrum_transient_pulse_gain': 1.0,
                                    'spectrum_unique_colors': True,
                                    'spectrum_visual_smoothing': 0.5,
                                    'spectrum_visual_smoothing_enabled': True,
                                    'spectrum_wave_amplitude': 0.5,
                                    'visualizers_enabled': True},
             'steam': {'enabled': False,
                       'privacy_mode': 'Rich',
                       'refresh_minutes': 6,
                       'show_connection_info_icon': True},
             'steam_progress': {'bg_color': [35, 35, 35, 255],
                                'bg_opacity': 0.3,
                                'border_color': [255, 255, 255, 255],
                                'border_opacity': 1.0,
                                'color': [255, 255, 255, 230],
                                'enabled': False,
                                'font_family': 'Inter',
                                'font_size': 14,
                                'margin': 30,
                                'monitor': 'ALL',
                                'position': 'Top Right',
                                'preferred_height': 180,
                                'preferred_width': 420,
                                'show_background': True},
             'weather': {'bg_color': [35, 35, 35, 255],
                         'bg_opacity': 0.3,
                         'border_color': [255, 255, 255, 255],
                         'border_opacity': 1.0,
                         'color': [255, 255, 255, 230],
                         'detail_icon_size': 16,
                         'enabled': True,
                         'font_family': 'Inter',
                         'font_size': 25,
                         'icon_alignment': 'RIGHT',
                         'icon_size': 96,
                         'location': '',
                         'margin': 30,
                         'monitor': 1,
                         'position': 'Bottom Right',
                         'show_background': True,
                         'show_condition_icon': True,
                         'show_details_row': True,
                         'show_forecast': True}},
 'workers': {'fft': {'enabled': False},
             'fft.enabled': False,
             'image': {'enabled': True},
             'image.enabled': True,
             'max_workers': 'auto',
             'rss': {'enabled': True},
             'rss.enabled': True,
             'transition': {'enabled': True},
             'transition.enabled': True}}
